<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="15">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>normalizer</name>
		<ret_bitwidth>0</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>8</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>regs_in_0</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>regs_in[0]</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>regs_in_1</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>regs_in[1]</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_3">
				<Value>
					<Obj>
						<type>1</type>
						<id>3</id>
						<name>regs_in_2</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>regs_in[2]</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_4">
				<Value>
					<Obj>
						<type>1</type>
						<id>4</id>
						<name>regs_in_3</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>regs_in[3]</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_5">
				<Value>
					<Obj>
						<type>1</type>
						<id>5</id>
						<name>regs_in_4</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>regs_in[4]</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_6">
				<Value>
					<Obj>
						<type>1</type>
						<id>6</id>
						<name>min_high</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>min_high</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_7">
				<Value>
					<Obj>
						<type>1</type>
						<id>7</id>
						<name>max_high</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>max_high</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>0</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_8">
				<Value>
					<Obj>
						<type>1</type>
						<id>8</id>
						<name>m_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>m.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<direction>1</direction>
				<if_type>4</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>44</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>19</id>
						<name>max_high_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>max_high</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>73</item>
					<item>74</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>20</id>
						<name>min_high_read</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>min_high</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>75</item>
					<item>76</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>27</id>
						<name>p_Val2_s</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>76</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="11" tracking_level="0" version="0">
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second class_id="12" tracking_level="0" version="0">
									<count>1</count>
									<item_version>0</item_version>
									<item class_id="13" tracking_level="0" version="0">
										<first class_id="14" tracking_level="0" version="0">
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>v</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>77</item>
					<item>78</item>
				</oprand_edges>
				<opcode>sub</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>28</id>
						<name>tmp</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>76</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>4</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>79</item>
				</oprand_edges>
				<opcode>trunc</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>29</id>
						<name>range_V</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>76</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>76</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>range.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>6</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>81</item>
					<item>82</item>
					<item>84</item>
				</oprand_edges>
				<opcode>bitconcatenate</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>30</id>
						<name>regs_in_0_read</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>86</item>
					<item>87</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>31</id>
						<name>tmp_4</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>88</item>
					<item>90</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_16">
				<Value>
					<Obj>
						<type>0</type>
						<id>32</id>
						<name>changed_load</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>91</item>
				</oprand_edges>
				<opcode>load</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_17">
				<Value>
					<Obj>
						<type>0</type>
						<id>33</id>
						<name>changed_load_s</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>92</item>
					<item>93</item>
					<item>94</item>
				</oprand_edges>
				<opcode>select</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_18">
				<Value>
					<Obj>
						<type>0</type>
						<id>34</id>
						<name>regs_in_1_read</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>95</item>
					<item>96</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_19">
				<Value>
					<Obj>
						<type>0</type>
						<id>35</id>
						<name>tmp_4_1</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>97</item>
					<item>98</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_20">
				<Value>
					<Obj>
						<type>0</type>
						<id>36</id>
						<name>tmp_1</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>99</item>
					<item>100</item>
				</oprand_edges>
				<opcode>or</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_21">
				<Value>
					<Obj>
						<type>0</type>
						<id>37</id>
						<name>not_tmp_4_1</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>101</item>
					<item>103</item>
				</oprand_edges>
				<opcode>xor</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_22">
				<Value>
					<Obj>
						<type>0</type>
						<id>38</id>
						<name>changed_new_1_cast</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>104</item>
				</oprand_edges>
				<opcode>zext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_23">
				<Value>
					<Obj>
						<type>0</type>
						<id>39</id>
						<name>changed_loc_1</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>105</item>
					<item>106</item>
					<item>108</item>
				</oprand_edges>
				<opcode>select</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_24">
				<Value>
					<Obj>
						<type>0</type>
						<id>40</id>
						<name>regs_in_2_read</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>109</item>
					<item>110</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_25">
				<Value>
					<Obj>
						<type>0</type>
						<id>41</id>
						<name>tmp_4_2</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>111</item>
					<item>112</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_26">
				<Value>
					<Obj>
						<type>0</type>
						<id>42</id>
						<name>changed_new_1_s</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>113</item>
					<item>114</item>
					<item>116</item>
				</oprand_edges>
				<opcode>select</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_27">
				<Value>
					<Obj>
						<type>0</type>
						<id>43</id>
						<name>changed_loc_1_s</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>117</item>
					<item>118</item>
					<item>119</item>
				</oprand_edges>
				<opcode>select</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_28">
				<Value>
					<Obj>
						<type>0</type>
						<id>44</id>
						<name>regs_in_3_read</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>120</item>
					<item>121</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_29">
				<Value>
					<Obj>
						<type>0</type>
						<id>45</id>
						<name>tmp_4_3</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>122</item>
					<item>123</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_30">
				<Value>
					<Obj>
						<type>0</type>
						<id>46</id>
						<name>tmp_8</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>124</item>
					<item>125</item>
				</oprand_edges>
				<opcode>or</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_31">
				<Value>
					<Obj>
						<type>0</type>
						<id>47</id>
						<name>tmp_9</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>126</item>
					<item>127</item>
				</oprand_edges>
				<opcode>or</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_32">
				<Value>
					<Obj>
						<type>0</type>
						<id>48</id>
						<name>tmp_3</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>128</item>
					<item>129</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_33">
				<Value>
					<Obj>
						<type>0</type>
						<id>49</id>
						<name>changed_new_3</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>130</item>
					<item>131</item>
					<item>133</item>
				</oprand_edges>
				<opcode>select</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_34">
				<Value>
					<Obj>
						<type>0</type>
						<id>50</id>
						<name>changed_loc_3</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>134</item>
					<item>135</item>
					<item>136</item>
				</oprand_edges>
				<opcode>select</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_35">
				<Value>
					<Obj>
						<type>0</type>
						<id>51</id>
						<name>tmp_2</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>64</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>137</item>
				</oprand_edges>
				<opcode>zext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_36">
				<Value>
					<Obj>
						<type>0</type>
						<id>52</id>
						<name>changed_load_t</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>3</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>138</item>
				</oprand_edges>
				<opcode>zext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_37">
				<Value>
					<Obj>
						<type>0</type>
						<id>53</id>
						<name></name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>83</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>83</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>139</item>
					<item>140</item>
					<item>141</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_38">
				<Value>
					<Obj>
						<type>0</type>
						<id>55</id>
						<name></name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>84</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>84</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>142</item>
					<item>143</item>
					<item>318</item>
				</oprand_edges>
				<opcode>store</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_39">
				<Value>
					<Obj>
						<type>0</type>
						<id>56</id>
						<name></name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>144</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_40">
				<Value>
					<Obj>
						<type>0</type>
						<id>58</id>
						<name>regs_in_load_phi</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>10</count>
					<item_version>0</item_version>
					<item>146</item>
					<item>147</item>
					<item>148</item>
					<item>149</item>
					<item>150</item>
					<item>151</item>
					<item>152</item>
					<item>153</item>
					<item>154</item>
					<item>155</item>
				</oprand_edges>
				<opcode>mux</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_41">
				<Value>
					<Obj>
						<type>0</type>
						<id>59</id>
						<name>p_Val2_1</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>v</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>156</item>
					<item>157</item>
				</oprand_edges>
				<opcode>sub</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_42">
				<Value>
					<Obj>
						<type>0</type>
						<id>60</id>
						<name>tmp_5</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>4</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>158</item>
				</oprand_edges>
				<opcode>trunc</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_43">
				<Value>
					<Obj>
						<type>0</type>
						<id>61</id>
						<name>tmp_6</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>160</item>
					<item>161</item>
					<item>163</item>
				</oprand_edges>
				<opcode>bitconcatenate</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_44">
				<Value>
					<Obj>
						<type>0</type>
						<id>62</id>
						<name>tmp_7</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>164</item>
				</oprand_edges>
				<opcode>zext</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_45">
				<Value>
					<Obj>
						<type>0</type>
						<id>63</id>
						<name>p_Val2_2</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>__Val2__</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>3</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>165</item>
					<item>166</item>
				</oprand_edges>
				<opcode>udiv</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_46">
				<Value>
					<Obj>
						<type>0</type>
						<id>64</id>
						<name>tmp_10</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>3</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>167</item>
				</oprand_edges>
				<opcode>trunc</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_47">
				<Value>
					<Obj>
						<type>0</type>
						<id>65</id>
						<name>tmp_s</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>169</item>
					<item>170</item>
					<item>172</item>
				</oprand_edges>
				<opcode>bitconcatenate</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_48">
				<Value>
					<Obj>
						<type>0</type>
						<id>66</id>
						<name>m_V_addr</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>16</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>173</item>
					<item>174</item>
				</oprand_edges>
				<opcode>getelementptr</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_49">
				<Value>
					<Obj>
						<type>0</type>
						<id>67</id>
						<name>m_V_addr_req</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>176</item>
					<item>177</item>
					<item>179</item>
				</oprand_edges>
				<opcode>writereq</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_50">
				<Value>
					<Obj>
						<type>0</type>
						<id>68</id>
						<name></name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>5</count>
					<item_version>0</item_version>
					<item>181</item>
					<item>182</item>
					<item>183</item>
					<item>184</item>
					<item>317</item>
				</oprand_edges>
				<opcode>write</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_51">
				<Value>
					<Obj>
						<type>0</type>
						<id>69</id>
						<name>m_V_addr_resp</name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>88</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>88</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>186</item>
					<item>187</item>
					<item>316</item>
				</oprand_edges>
				<opcode>writeresp</opcode>
				<m_Display>0</m_Display>
			</item>
			<item class_id_reference="9" object_id="_52">
				<Value>
					<Obj>
						<type>0</type>
						<id>70</id>
						<name></name>
						<fileName>normalizer.cpp</fileName>
						<fileDirectory>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</fileDirectory>
						<lineNumber>90</lineNumber>
						<contextFuncName>normalizer</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>/home/brennan/Documents/pynq-copter/pynqcopter/ip/normalizer</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>normalizer.cpp</first>
											<second>normalizer</second>
										</first>
										<second>90</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>0</count>
					<item_version>0</item_version>
				</oprand_edges>
				<opcode>ret</opcode>
				<m_Display>0</m_Display>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>9</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_53">
				<Value>
					<Obj>
						<type>2</type>
						<id>83</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_54">
				<Value>
					<Obj>
						<type>2</type>
						<id>89</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_55">
				<Value>
					<Obj>
						<type>2</type>
						<id>102</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_56">
				<Value>
					<Obj>
						<type>2</type>
						<id>107</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_57">
				<Value>
					<Obj>
						<type>2</type>
						<id>115</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>2</content>
			</item>
			<item class_id_reference="16" object_id="_58">
				<Value>
					<Obj>
						<type>2</type>
						<id>132</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>3</content>
			</item>
			<item class_id_reference="16" object_id="_59">
				<Value>
					<Obj>
						<type>2</type>
						<id>162</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>4</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_60">
				<Value>
					<Obj>
						<type>2</type>
						<id>171</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>13</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_61">
				<Value>
					<Obj>
						<type>2</type>
						<id>178</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>3</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_62">
				<Obj>
					<type>3</type>
					<id>54</id>
					<name>._crit_edge.0</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>29</count>
					<item_version>0</item_version>
					<item>19</item>
					<item>20</item>
					<item>27</item>
					<item>28</item>
					<item>29</item>
					<item>30</item>
					<item>31</item>
					<item>32</item>
					<item>33</item>
					<item>34</item>
					<item>35</item>
					<item>36</item>
					<item>37</item>
					<item>38</item>
					<item>39</item>
					<item>40</item>
					<item>41</item>
					<item>42</item>
					<item>43</item>
					<item>44</item>
					<item>45</item>
					<item>46</item>
					<item>47</item>
					<item>48</item>
					<item>49</item>
					<item>50</item>
					<item>51</item>
					<item>52</item>
					<item>53</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_63">
				<Obj>
					<type>3</type>
					<id>57</id>
					<name>mergeST</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>2</count>
					<item_version>0</item_version>
					<item>55</item>
					<item>56</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_64">
				<Obj>
					<type>3</type>
					<id>71</id>
					<name>._crit_edge.3.new</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>13</count>
					<item_version>0</item_version>
					<item>58</item>
					<item>59</item>
					<item>60</item>
					<item>61</item>
					<item>62</item>
					<item>63</item>
					<item>64</item>
					<item>65</item>
					<item>66</item>
					<item>67</item>
					<item>68</item>
					<item>69</item>
					<item>70</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>91</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_65">
				<id>74</id>
				<edge_type>1</edge_type>
				<source_obj>7</source_obj>
				<sink_obj>19</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_66">
				<id>76</id>
				<edge_type>1</edge_type>
				<source_obj>6</source_obj>
				<sink_obj>20</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_67">
				<id>77</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>27</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_68">
				<id>78</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>27</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_69">
				<id>79</id>
				<edge_type>1</edge_type>
				<source_obj>27</source_obj>
				<sink_obj>28</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_70">
				<id>82</id>
				<edge_type>1</edge_type>
				<source_obj>28</source_obj>
				<sink_obj>29</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_71">
				<id>84</id>
				<edge_type>1</edge_type>
				<source_obj>83</source_obj>
				<sink_obj>29</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_72">
				<id>87</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>30</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_73">
				<id>88</id>
				<edge_type>1</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>31</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_74">
				<id>90</id>
				<edge_type>1</edge_type>
				<source_obj>89</source_obj>
				<sink_obj>31</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_75">
				<id>91</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>32</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_76">
				<id>92</id>
				<edge_type>1</edge_type>
				<source_obj>31</source_obj>
				<sink_obj>33</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_77">
				<id>93</id>
				<edge_type>1</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>33</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_78">
				<id>94</id>
				<edge_type>1</edge_type>
				<source_obj>83</source_obj>
				<sink_obj>33</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_79">
				<id>96</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>34</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_80">
				<id>97</id>
				<edge_type>1</edge_type>
				<source_obj>34</source_obj>
				<sink_obj>35</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_81">
				<id>98</id>
				<edge_type>1</edge_type>
				<source_obj>89</source_obj>
				<sink_obj>35</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_82">
				<id>99</id>
				<edge_type>1</edge_type>
				<source_obj>34</source_obj>
				<sink_obj>36</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_83">
				<id>100</id>
				<edge_type>1</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>36</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_84">
				<id>101</id>
				<edge_type>1</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>37</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_85">
				<id>103</id>
				<edge_type>1</edge_type>
				<source_obj>102</source_obj>
				<sink_obj>37</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_86">
				<id>104</id>
				<edge_type>1</edge_type>
				<source_obj>37</source_obj>
				<sink_obj>38</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_87">
				<id>105</id>
				<edge_type>1</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>39</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_88">
				<id>106</id>
				<edge_type>1</edge_type>
				<source_obj>33</source_obj>
				<sink_obj>39</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_89">
				<id>108</id>
				<edge_type>1</edge_type>
				<source_obj>107</source_obj>
				<sink_obj>39</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_90">
				<id>110</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>40</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_91">
				<id>111</id>
				<edge_type>1</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>41</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_92">
				<id>112</id>
				<edge_type>1</edge_type>
				<source_obj>89</source_obj>
				<sink_obj>41</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_93">
				<id>113</id>
				<edge_type>1</edge_type>
				<source_obj>41</source_obj>
				<sink_obj>42</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_94">
				<id>114</id>
				<edge_type>1</edge_type>
				<source_obj>38</source_obj>
				<sink_obj>42</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_95">
				<id>116</id>
				<edge_type>1</edge_type>
				<source_obj>115</source_obj>
				<sink_obj>42</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_96">
				<id>117</id>
				<edge_type>1</edge_type>
				<source_obj>41</source_obj>
				<sink_obj>43</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_97">
				<id>118</id>
				<edge_type>1</edge_type>
				<source_obj>39</source_obj>
				<sink_obj>43</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_98">
				<id>119</id>
				<edge_type>1</edge_type>
				<source_obj>115</source_obj>
				<sink_obj>43</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_99">
				<id>121</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>44</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_100">
				<id>122</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>45</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_101">
				<id>123</id>
				<edge_type>1</edge_type>
				<source_obj>89</source_obj>
				<sink_obj>45</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_102">
				<id>124</id>
				<edge_type>1</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>46</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_103">
				<id>125</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>46</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_104">
				<id>126</id>
				<edge_type>1</edge_type>
				<source_obj>46</source_obj>
				<sink_obj>47</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_105">
				<id>127</id>
				<edge_type>1</edge_type>
				<source_obj>36</source_obj>
				<sink_obj>47</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_106">
				<id>128</id>
				<edge_type>1</edge_type>
				<source_obj>47</source_obj>
				<sink_obj>48</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_107">
				<id>129</id>
				<edge_type>1</edge_type>
				<source_obj>89</source_obj>
				<sink_obj>48</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_108">
				<id>130</id>
				<edge_type>1</edge_type>
				<source_obj>45</source_obj>
				<sink_obj>49</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_109">
				<id>131</id>
				<edge_type>1</edge_type>
				<source_obj>42</source_obj>
				<sink_obj>49</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_110">
				<id>133</id>
				<edge_type>1</edge_type>
				<source_obj>132</source_obj>
				<sink_obj>49</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_111">
				<id>134</id>
				<edge_type>1</edge_type>
				<source_obj>45</source_obj>
				<sink_obj>50</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_112">
				<id>135</id>
				<edge_type>1</edge_type>
				<source_obj>43</source_obj>
				<sink_obj>50</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_113">
				<id>136</id>
				<edge_type>1</edge_type>
				<source_obj>132</source_obj>
				<sink_obj>50</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_114">
				<id>137</id>
				<edge_type>1</edge_type>
				<source_obj>50</source_obj>
				<sink_obj>51</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_115">
				<id>138</id>
				<edge_type>1</edge_type>
				<source_obj>50</source_obj>
				<sink_obj>52</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_116">
				<id>139</id>
				<edge_type>1</edge_type>
				<source_obj>48</source_obj>
				<sink_obj>53</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_117">
				<id>140</id>
				<edge_type>2</edge_type>
				<source_obj>57</source_obj>
				<sink_obj>53</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_118">
				<id>141</id>
				<edge_type>2</edge_type>
				<source_obj>71</source_obj>
				<sink_obj>53</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_119">
				<id>142</id>
				<edge_type>1</edge_type>
				<source_obj>49</source_obj>
				<sink_obj>55</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_120">
				<id>143</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>55</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_121">
				<id>144</id>
				<edge_type>2</edge_type>
				<source_obj>71</source_obj>
				<sink_obj>56</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_122">
				<id>147</id>
				<edge_type>1</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_123">
				<id>148</id>
				<edge_type>1</edge_type>
				<source_obj>34</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_124">
				<id>149</id>
				<edge_type>1</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_125">
				<id>150</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_126">
				<id>151</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_127">
				<id>152</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_128">
				<id>153</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_129">
				<id>154</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_130">
				<id>155</id>
				<edge_type>1</edge_type>
				<source_obj>52</source_obj>
				<sink_obj>58</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_131">
				<id>156</id>
				<edge_type>1</edge_type>
				<source_obj>58</source_obj>
				<sink_obj>59</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_132">
				<id>157</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>59</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_133">
				<id>158</id>
				<edge_type>1</edge_type>
				<source_obj>59</source_obj>
				<sink_obj>60</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_134">
				<id>161</id>
				<edge_type>1</edge_type>
				<source_obj>60</source_obj>
				<sink_obj>61</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_135">
				<id>163</id>
				<edge_type>1</edge_type>
				<source_obj>162</source_obj>
				<sink_obj>61</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_136">
				<id>164</id>
				<edge_type>1</edge_type>
				<source_obj>29</source_obj>
				<sink_obj>62</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_137">
				<id>165</id>
				<edge_type>1</edge_type>
				<source_obj>61</source_obj>
				<sink_obj>63</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_138">
				<id>166</id>
				<edge_type>1</edge_type>
				<source_obj>62</source_obj>
				<sink_obj>63</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_139">
				<id>167</id>
				<edge_type>1</edge_type>
				<source_obj>63</source_obj>
				<sink_obj>64</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_140">
				<id>170</id>
				<edge_type>1</edge_type>
				<source_obj>64</source_obj>
				<sink_obj>65</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_141">
				<id>172</id>
				<edge_type>1</edge_type>
				<source_obj>171</source_obj>
				<sink_obj>65</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_142">
				<id>173</id>
				<edge_type>1</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>66</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_143">
				<id>174</id>
				<edge_type>1</edge_type>
				<source_obj>51</source_obj>
				<sink_obj>66</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_144">
				<id>177</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>67</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_145">
				<id>179</id>
				<edge_type>1</edge_type>
				<source_obj>178</source_obj>
				<sink_obj>67</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_146">
				<id>182</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>68</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_147">
				<id>183</id>
				<edge_type>1</edge_type>
				<source_obj>65</source_obj>
				<sink_obj>68</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_148">
				<id>184</id>
				<edge_type>1</edge_type>
				<source_obj>132</source_obj>
				<sink_obj>68</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_149">
				<id>187</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>69</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_150">
				<id>313</id>
				<edge_type>2</edge_type>
				<source_obj>54</source_obj>
				<sink_obj>71</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_151">
				<id>314</id>
				<edge_type>2</edge_type>
				<source_obj>54</source_obj>
				<sink_obj>57</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_152">
				<id>315</id>
				<edge_type>2</edge_type>
				<source_obj>57</source_obj>
				<sink_obj>71</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_153">
				<id>316</id>
				<edge_type>4</edge_type>
				<source_obj>68</source_obj>
				<sink_obj>69</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_154">
				<id>317</id>
				<edge_type>4</edge_type>
				<source_obj>67</source_obj>
				<sink_obj>68</sink_obj>
			</item>
			<item class_id_reference="20" object_id="_155">
				<id>318</id>
				<edge_type>4</edge_type>
				<source_obj>32</source_obj>
				<sink_obj>55</sink_obj>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_156">
			<mId>1</mId>
			<mTag>normalizer</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>3</count>
				<item_version>0</item_version>
				<item>54</item>
				<item>57</item>
				<item>71</item>
			</basic_blocks>
			<mII>1</mII>
			<mDepth>22</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>21</mMinLatency>
			<mMaxLatency>-1</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="26" tracking_level="0" version="0">
		<count>44</count>
		<item_version>0</item_version>
		<item class_id="27" tracking_level="0" version="0">
			<first>19</first>
			<second class_id="28" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>20</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>27</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>28</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>29</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>30</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>31</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>32</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>33</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>34</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>35</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>36</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>37</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>38</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>39</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>40</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>41</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>42</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>43</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>44</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>45</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>46</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>47</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>48</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>49</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>50</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>51</first>
			<second>
				<first>15</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>52</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>53</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>55</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>56</first>
			<second>
				<first>21</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>58</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>59</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>60</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>61</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>62</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>63</first>
			<second>
				<first>4</first>
				<second>11</second>
			</second>
		</item>
		<item>
			<first>64</first>
			<second>
				<first>16</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>65</first>
			<second>
				<first>16</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>66</first>
			<second>
				<first>15</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>67</first>
			<second>
				<first>15</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>68</first>
			<second>
				<first>16</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>69</first>
			<second>
				<first>17</first>
				<second>4</second>
			</second>
		</item>
		<item>
			<first>70</first>
			<second>
				<first>21</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="29" tracking_level="0" version="0">
		<count>3</count>
		<item_version>0</item_version>
		<item class_id="30" tracking_level="0" version="0">
			<first>54</first>
			<second class_id="31" tracking_level="0" version="0">
				<first>0</first>
				<second>21</second>
			</second>
		</item>
		<item>
			<first>57</first>
			<second>
				<first>1</first>
				<second>21</second>
			</second>
		</item>
		<item>
			<first>71</first>
			<second>
				<first>0</first>
				<second>21</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="32" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="33" tracking_level="1" version="0" object_id="_157">
			<region_name>normalizer</region_name>
			<basic_blocks>
				<count>3</count>
				<item_version>0</item_version>
				<item>54</item>
				<item>57</item>
				<item>71</item>
			</basic_blocks>
			<nodes>
				<count>0</count>
				<item_version>0</item_version>
			</nodes>
			<anchor_node>-1</anchor_node>
			<region_type>8</region_type>
			<interval>1</interval>
			<pipe_depth>22</pipe_depth>
		</item>
	</regions>
	<dp_fu_nodes class_id="34" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="37" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core class_id="38" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

