<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="15">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>ctrlloop</name>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>5</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>IOMEM</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>iomem.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>4</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>regs_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>regs.V</originalName>
              <rtlName/>
              <coreName>RAM_1P</coreName>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>1</if_type>
          <array_size>128</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_3">
          <Value>
            <Obj>
              <type>1</type>
              <id>3</id>
              <name>buttons_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>op.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_4">
          <Value>
            <Obj>
              <type>1</type>
              <id>4</id>
              <name>interrupt_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_5">
          <Value>
            <Obj>
              <type>1</type>
              <id>5</id>
              <name>leds_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>leds.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>18</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>12</id>
              <name>buttons_V_read</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>op.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>47</item>
            <item>48</item>
          </oprand_edges>
          <opcode>read</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>13</id>
              <name>dummy</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>dummy</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>50</item>
          </oprand_edges>
          <opcode>alloca</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>22</id>
              <name>led_state_V_load</name>
              <fileName>ctrlloop.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>83</lineNumber>
              <contextFuncName>ctrlloop</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="11" tracking_level="0" version="0">
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second class_id="12" tracking_level="0" version="0">
                    <count>1</count>
                    <item_version>0</item_version>
                    <item class_id="13" tracking_level="0" version="0">
                      <first class_id="14" tracking_level="0" version="0">
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>83</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>51</item>
          </oprand_edges>
          <opcode>load</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>23</id>
              <name>led_state_V_assign</name>
              <fileName>ctrlloop.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>83</lineNumber>
              <contextFuncName>ctrlloop</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>83</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>led_state_V_assign_fu_121_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>52</item>
            <item>54</item>
          </oprand_edges>
          <opcode>add</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>24</id>
              <name/>
              <fileName>ctrlloop.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>83</lineNumber>
              <contextFuncName>ctrlloop</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>83</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>55</item>
            <item>56</item>
            <item>239</item>
          </oprand_edges>
          <opcode>store</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>25</id>
              <name/>
              <fileName>ctrlloop.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>85</lineNumber>
              <contextFuncName>ctrlloop</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>85</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>58</item>
            <item>59</item>
            <item>60</item>
          </oprand_edges>
          <opcode>write</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>26</id>
              <name>p_s</name>
              <fileName>ctrlloop.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>88</lineNumber>
              <contextFuncName>ctrlloop</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>88</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>regs_V_d0</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>61</item>
          </oprand_edges>
          <opcode>zext</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>27</id>
              <name>regs_V_addr</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>7</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>62</item>
            <item>64</item>
            <item>65</item>
          </oprand_edges>
          <opcode>getelementptr</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_14">
          <Value>
            <Obj>
              <type>0</type>
              <id>28</id>
              <name/>
              <fileName>ctrlloop.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>88</lineNumber>
              <contextFuncName>ctrlloop</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>88</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>66</item>
            <item>67</item>
          </oprand_edges>
          <opcode>store</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_15">
          <Value>
            <Obj>
              <type>0</type>
              <id>31</id>
              <name/>
              <fileName>./ctrlloop.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>57</lineNumber>
              <contextFuncName>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>./ctrlloop.hpp</first>
                        <second>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</second>
                      </first>
                      <second>57</second>
                    </item>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>92</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>68</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_16">
          <Value>
            <Obj>
              <type>0</type>
              <id>33</id>
              <name>p_014_0_i</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>ctr.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>27</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>70</item>
            <item>71</item>
            <item>72</item>
            <item>73</item>
          </oprand_edges>
          <opcode>phi</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_17">
          <Value>
            <Obj>
              <type>0</type>
              <id>34</id>
              <name>tmp_1</name>
              <fileName>./ctrlloop.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>57</lineNumber>
              <contextFuncName>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>./ctrlloop.hpp</first>
                        <second>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</second>
                      </first>
                      <second>57</second>
                    </item>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>92</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_1_fu_139_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>74</item>
            <item>76</item>
          </oprand_edges>
          <opcode>icmp</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_18">
          <Value>
            <Obj>
              <type>0</type>
              <id>36</id>
              <name>ctr_V</name>
              <fileName>./ctrlloop.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>57</lineNumber>
              <contextFuncName>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>./ctrlloop.hpp</first>
                        <second>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</second>
                      </first>
                      <second>57</second>
                    </item>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>92</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>ctr.V</originalName>
              <rtlName>ctr_V_fu_145_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>27</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>77</item>
            <item>79</item>
          </oprand_edges>
          <opcode>add</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_19">
          <Value>
            <Obj>
              <type>0</type>
              <id>37</id>
              <name/>
              <fileName>./ctrlloop.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>57</lineNumber>
              <contextFuncName>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>./ctrlloop.hpp</first>
                        <second>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</second>
                      </first>
                      <second>57</second>
                    </item>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>92</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>80</item>
            <item>81</item>
            <item>82</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_20">
          <Value>
            <Obj>
              <type>0</type>
              <id>39</id>
              <name>dummy_1</name>
              <fileName>./ctrlloop.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>58</lineNumber>
              <contextFuncName>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>./ctrlloop.hpp</first>
                        <second>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</second>
                      </first>
                      <second>58</second>
                    </item>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>92</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>dummy</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>8</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>83</item>
          </oprand_edges>
          <opcode>load</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_21">
          <Value>
            <Obj>
              <type>0</type>
              <id>40</id>
              <name/>
              <fileName>./ctrlloop.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>58</lineNumber>
              <contextFuncName>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>./ctrlloop.hpp</first>
                        <second>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</second>
                      </first>
                      <second>58</second>
                    </item>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>92</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>84</item>
            <item>85</item>
            <item>240</item>
          </oprand_edges>
          <opcode>store</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_22">
          <Value>
            <Obj>
              <type>0</type>
              <id>41</id>
              <name/>
              <fileName>./ctrlloop.hpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>57</lineNumber>
              <contextFuncName>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>./ctrlloop.hpp</first>
                        <second>delay_until_ms&amp;lt;1000, 100000000&amp;gt;</second>
                      </first>
                      <second>57</second>
                    </item>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>92</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>86</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_23">
          <Value>
            <Obj>
              <type>0</type>
              <id>44</id>
              <name/>
              <fileName>ctrlloop.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>93</lineNumber>
              <contextFuncName>ctrlloop</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/iavendano/pynq-copter/pynqcopter/ip/ctrlloop</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>ctrlloop.cpp</first>
                        <second>ctrlloop</second>
                      </first>
                      <second>93</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>6</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_24">
          <Value>
            <Obj>
              <type>2</type>
              <id>49</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>64</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_25">
          <Value>
            <Obj>
              <type>2</type>
              <id>53</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_26">
          <Value>
            <Obj>
              <type>2</type>
              <id>63</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>64</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_27">
          <Value>
            <Obj>
              <type>2</type>
              <id>69</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>27</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_28">
          <Value>
            <Obj>
              <type>2</type>
              <id>75</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>27</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>100000000</content>
        </item>
        <item class_id_reference="16" object_id="_29">
          <Value>
            <Obj>
              <type>2</type>
              <id>78</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>27</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_30">
          <Obj>
            <type>3</type>
            <id>32</id>
            <name>codeRepl</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>10</count>
            <item_version>0</item_version>
            <item>12</item>
            <item>13</item>
            <item>22</item>
            <item>23</item>
            <item>24</item>
            <item>25</item>
            <item>26</item>
            <item>27</item>
            <item>28</item>
            <item>31</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_31">
          <Obj>
            <type>3</type>
            <id>38</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>4</count>
            <item_version>0</item_version>
            <item>33</item>
            <item>34</item>
            <item>36</item>
            <item>37</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_32">
          <Obj>
            <type>3</type>
            <id>42</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>3</count>
            <item_version>0</item_version>
            <item>39</item>
            <item>40</item>
            <item>41</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_33">
          <Obj>
            <type>3</type>
            <id>45</id>
            <name>delay_until_ms&lt;1000ull, 100000000ull&gt;.exit</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>1</count>
            <item_version>0</item_version>
            <item>44</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>37</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_34">
          <id>48</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>12</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>50</id>
          <edge_type>1</edge_type>
          <source_obj>49</source_obj>
          <sink_obj>13</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>51</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>22</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>52</id>
          <edge_type>1</edge_type>
          <source_obj>22</source_obj>
          <sink_obj>23</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>54</id>
          <edge_type>1</edge_type>
          <source_obj>53</source_obj>
          <sink_obj>23</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>55</id>
          <edge_type>1</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>24</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>56</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>24</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>59</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>25</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>60</id>
          <edge_type>1</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>25</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>61</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>26</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>62</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>27</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>64</id>
          <edge_type>1</edge_type>
          <source_obj>63</source_obj>
          <sink_obj>27</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>65</id>
          <edge_type>1</edge_type>
          <source_obj>63</source_obj>
          <sink_obj>27</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>66</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>28</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>67</id>
          <edge_type>1</edge_type>
          <source_obj>27</source_obj>
          <sink_obj>28</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>68</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>31</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>70</id>
          <edge_type>1</edge_type>
          <source_obj>69</source_obj>
          <sink_obj>33</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>71</id>
          <edge_type>2</edge_type>
          <source_obj>32</source_obj>
          <sink_obj>33</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>72</id>
          <edge_type>1</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>33</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>73</id>
          <edge_type>2</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>33</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>74</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>34</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>76</id>
          <edge_type>1</edge_type>
          <source_obj>75</source_obj>
          <sink_obj>34</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>77</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>36</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>79</id>
          <edge_type>1</edge_type>
          <source_obj>78</source_obj>
          <sink_obj>36</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>80</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>37</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>81</id>
          <edge_type>2</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>37</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>82</id>
          <edge_type>2</edge_type>
          <source_obj>45</source_obj>
          <sink_obj>37</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>83</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>39</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_62">
          <id>84</id>
          <edge_type>1</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>40</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_63">
          <id>85</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>40</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_64">
          <id>86</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>41</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_65">
          <id>235</id>
          <edge_type>2</edge_type>
          <source_obj>32</source_obj>
          <sink_obj>38</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_66">
          <id>236</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>45</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_67">
          <id>237</id>
          <edge_type>2</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_68">
          <id>238</id>
          <edge_type>2</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>38</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_69">
          <id>239</id>
          <edge_type>4</edge_type>
          <source_obj>22</source_obj>
          <sink_obj>24</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_70">
          <id>240</id>
          <edge_type>4</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>40</sink_obj>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_71">
        <mId>1</mId>
        <mTag>ctrlloop</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>3</count>
          <item_version>0</item_version>
          <item>2</item>
          <item>3</item>
          <item>4</item>
        </sub_regions>
        <basic_blocks>
          <count>0</count>
          <item_version>0</item_version>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>100000001</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_72">
        <mId>2</mId>
        <mTag>Entry</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>32</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_73">
        <mId>3</mId>
        <mTag>Loop 1</mTag>
        <mType>1</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>2</count>
          <item_version>0</item_version>
          <item>38</item>
          <item>42</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>100000000</mMinTripCount>
        <mMaxTripCount>100000000</mMaxTripCount>
        <mMinLatency>100000000</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_74">
        <mId>4</mId>
        <mTag>Return</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>45</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_75">
      <states class_id="25" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_76">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>25</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_77">
              <id>7</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_78">
              <id>8</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_79">
              <id>9</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_80">
              <id>10</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_81">
              <id>11</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_82">
              <id>12</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_83">
              <id>13</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_84">
              <id>14</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_85">
              <id>15</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_86">
              <id>16</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_87">
              <id>17</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_88">
              <id>18</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_89">
              <id>19</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_90">
              <id>20</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_91">
              <id>21</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_92">
              <id>22</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_93">
              <id>23</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_94">
              <id>24</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_95">
              <id>25</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_96">
              <id>26</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_97">
              <id>27</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_98">
              <id>28</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_99">
              <id>29</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_100">
              <id>30</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_101">
              <id>31</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_102">
          <id>2</id>
          <operations>
            <count>10</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_103">
              <id>33</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_104">
              <id>34</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_105">
              <id>35</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_106">
              <id>36</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_107">
              <id>37</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_108">
              <id>39</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_109">
              <id>40</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_110">
              <id>41</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_111">
              <id>43</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_112">
              <id>44</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_113">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>7</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_114">
          <inState>2</inState>
          <outState>2</outState>
          <condition>
            <id>9</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="34" tracking_level="0" version="0">
                  <first class_id="35" tracking_level="0" version="0">
                    <first>34</first>
                    <second>0</second>
                  </first>
                  <second>1</second>
                </item>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="36" tracking_level="1" version="0" object_id="_115">
      <dp_component_resource class_id="37" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="38" tracking_level="0" version="0">
          <first>ctrlloop_CTRL_s_axi_U (ctrlloop_CTRL_s_axi)</first>
          <second class_id="39" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="40" tracking_level="0" version="0">
              <first>BRAM</first>
              <second>2</second>
            </item>
            <item>
              <first>FF</first>
              <second>116</second>
            </item>
            <item>
              <first>LUT</first>
              <second>110</second>
            </item>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>ctr_V_fu_145_p2 ( + ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>27</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>34</second>
            </item>
          </second>
        </item>
        <item>
          <first>led_state_V_assign_fu_121_p2 ( + ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>4</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>13</second>
            </item>
          </second>
        </item>
        <item>
          <first>tmp_1_fu_139_p2 ( icmp ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>27</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>27</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>18</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>3</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>3</second>
            </item>
            <item>
              <first>LUT</first>
              <second>15</second>
            </item>
          </second>
        </item>
        <item>
          <first>leds_V</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>4</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>8</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>p_014_0_i_reg_106</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>27</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>54</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>4</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>2</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>2</second>
            </item>
          </second>
        </item>
        <item>
          <first>led_state_V</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>4</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>4</second>
            </item>
          </second>
        </item>
        <item>
          <first>leds_V_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>4</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>4</second>
            </item>
          </second>
        </item>
        <item>
          <first>p_014_0_i_reg_106</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>27</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>27</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>ctrlloop_CTRL_s_axi_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="41" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_map>
      <dp_expression_map>
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="42" tracking_level="0" version="0">
          <first>ctr_V_fu_145_p2 ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>36</item>
          </second>
        </item>
        <item>
          <first>led_state_V_assign_fu_121_p2 ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>23</item>
          </second>
        </item>
        <item>
          <first>tmp_1_fu_139_p2 ( icmp ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>34</item>
          </second>
        </item>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="43" tracking_level="0" version="0">
      <count>18</count>
      <item_version>0</item_version>
      <item class_id="44" tracking_level="0" version="0">
        <first>12</first>
        <second class_id="45" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>13</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>22</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>23</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>24</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>25</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>26</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>27</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>28</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>31</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>33</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>34</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>37</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>39</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>40</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>41</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>44</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="46" tracking_level="0" version="0">
      <count>4</count>
      <item_version>0</item_version>
      <item class_id="47" tracking_level="0" version="0">
        <first>32</first>
        <second class_id="48" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>38</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>42</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>45</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="49" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="50" tracking_level="1" version="0" object_id="_116">
        <region_name>delay_until_ms&lt;1000ull, 100000000ull&gt;.region</region_name>
        <basic_blocks>
          <count>4</count>
          <item_version>0</item_version>
          <item>32</item>
          <item>45</item>
          <item>38</item>
          <item>42</item>
        </basic_blocks>
        <nodes>
          <count>12</count>
          <item_version>0</item_version>
          <item>29</item>
          <item>30</item>
          <item>31</item>
          <item>43</item>
          <item>33</item>
          <item>34</item>
          <item>35</item>
          <item>36</item>
          <item>37</item>
          <item>39</item>
          <item>40</item>
          <item>41</item>
        </nodes>
        <anchor_node>29</anchor_node>
        <region_type>1</region_type>
        <interval>0</interval>
        <pipe_depth>0</pipe_depth>
      </item>
    </regions>
    <dp_fu_nodes class_id="51" tracking_level="0" version="0">
      <count>14</count>
      <item_version>0</item_version>
      <item class_id="52" tracking_level="0" version="0">
        <first>76</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
      <item>
        <first>80</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>86</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>25</item>
        </second>
      </item>
      <item>
        <first>93</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>27</item>
        </second>
      </item>
      <item>
        <first>101</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>28</item>
        </second>
      </item>
      <item>
        <first>110</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>117</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>22</item>
        </second>
      </item>
      <item>
        <first>121</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>23</item>
        </second>
      </item>
      <item>
        <first>128</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>24</item>
        </second>
      </item>
      <item>
        <first>134</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>26</item>
        </second>
      </item>
      <item>
        <first>139</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
      <item>
        <first>145</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>151</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
      <item>
        <first>154</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>40</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="54" tracking_level="0" version="0">
      <count>7</count>
      <item_version>0</item_version>
      <item class_id="55" tracking_level="0" version="0">
        <first>ctr_V_fu_145</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>dummy_fu_76</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
      <item>
        <first>led_state_V_assign_fu_121</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>23</item>
        </second>
      </item>
      <item>
        <first>p_014_0_i_phi_fu_110</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>p_s_fu_134</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>26</item>
        </second>
      </item>
      <item>
        <first>regs_V_addr_gep_fu_93</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>27</item>
        </second>
      </item>
      <item>
        <first>tmp_1_fu_139</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>6</count>
      <item_version>0</item_version>
      <item>
        <first>StgValue_20_store_fu_128</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>24</item>
        </second>
      </item>
      <item>
        <first>StgValue_21_write_fu_86</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>25</item>
        </second>
      </item>
      <item>
        <first>StgValue_34_store_fu_154</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>40</item>
        </second>
      </item>
      <item>
        <first>buttons_V_read_read_fu_80</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>dummy_1_load_fu_151</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
      <item>
        <first>led_state_V_load_load_fu_117</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>22</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="56" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="57" tracking_level="0" version="0">
        <first class_id="58" tracking_level="0" version="0">
          <first>regs_V</first>
          <second>0</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>28</item>
        </second>
      </item>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>106</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>159</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
      <item>
        <first>168</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>ctr_V_reg_168</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>dummy_reg_159</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
      <item>
        <first>p_014_0_i_reg_106</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>106</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>p_014_0_i_reg_106</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="59" tracking_level="0" version="0">
      <count>5</count>
      <item_version>0</item_version>
      <item class_id="60" tracking_level="0" version="0">
        <first>IOMEM</first>
        <second>
          <count>0</count>
          <item_version>0</item_version>
        </second>
      </item>
      <item>
        <first>buttons_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>12</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>interrupt_V</first>
        <second>
          <count>0</count>
          <item_version>0</item_version>
        </second>
      </item>
      <item>
        <first>leds_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>write</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>25</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>regs_V(p0)</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>store</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>28</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core class_id="61" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="62" tracking_level="0" version="0">
        <first>2</first>
        <second>RAM_1P</second>
      </item>
    </port2core>
    <node2core>
      <count>0</count>
      <item_version>0</item_version>
    </node2core>
  </syndb>
</boost_serialization>
