# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/iavendano/pynq-copter/pynqcopter/iicComm4/iicComm4/iicComm4.srcs/sources_1/bd/iicComm4/ip/iicComm4_processing_system7_0_0/iicComm4_processing_system7_0_0.xci
# IP: The module: 'iicComm4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iavendano/pynq-copter/pynqcopter/iicComm4/iicComm4/iicComm4.srcs/sources_1/bd/iicComm4/ip/iicComm4_processing_system7_0_0/iicComm4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'iicComm4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/iavendano/pynq-copter/pynqcopter/iicComm4/iicComm4/iicComm4.srcs/sources_1/bd/iicComm4/ip/iicComm4_processing_system7_0_0/iicComm4_processing_system7_0_0.xci
# IP: The module: 'iicComm4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iavendano/pynq-copter/pynqcopter/iicComm4/iicComm4/iicComm4.srcs/sources_1/bd/iicComm4/ip/iicComm4_processing_system7_0_0/iicComm4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'iicComm4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
