# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/pwm_system_ila_0_0.xci
# IP: The module: 'pwm_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/bd_6994.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994 || ORIG_REF_NAME==bd_6994} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_0/bd_6994_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_ila_lib_0 || ORIG_REF_NAME==bd_6994_ila_lib_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_1/bd_6994_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_g_inst_0 || ORIG_REF_NAME==bd_6994_g_inst_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_2/bd_6994_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_aw_0 || ORIG_REF_NAME==bd_6994_slot_0_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_3/bd_6994_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_w_0 || ORIG_REF_NAME==bd_6994_slot_0_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_4/bd_6994_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_b_0 || ORIG_REF_NAME==bd_6994_slot_0_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_5/bd_6994_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_ar_0 || ORIG_REF_NAME==bd_6994_slot_0_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_6/bd_6994_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_r_0 || ORIG_REF_NAME==bd_6994_slot_0_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_7/bd_6994_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_aw_0 || ORIG_REF_NAME==bd_6994_slot_1_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_8/bd_6994_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_w_0 || ORIG_REF_NAME==bd_6994_slot_1_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_9/bd_6994_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_b_0 || ORIG_REF_NAME==bd_6994_slot_1_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_10/bd_6994_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_ar_0 || ORIG_REF_NAME==bd_6994_slot_1_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_11/bd_6994_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_r_0 || ORIG_REF_NAME==bd_6994_slot_1_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_12/bd_6994_slot_2_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_aw_0 || ORIG_REF_NAME==bd_6994_slot_2_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_13/bd_6994_slot_2_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_w_0 || ORIG_REF_NAME==bd_6994_slot_2_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_14/bd_6994_slot_2_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_b_0 || ORIG_REF_NAME==bd_6994_slot_2_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_15/bd_6994_slot_2_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_ar_0 || ORIG_REF_NAME==bd_6994_slot_2_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_16/bd_6994_slot_2_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_r_0 || ORIG_REF_NAME==bd_6994_slot_2_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_17/bd_6994_slot_3_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_aw_0 || ORIG_REF_NAME==bd_6994_slot_3_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_18/bd_6994_slot_3_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_w_0 || ORIG_REF_NAME==bd_6994_slot_3_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_19/bd_6994_slot_3_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_b_0 || ORIG_REF_NAME==bd_6994_slot_3_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_20/bd_6994_slot_3_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_ar_0 || ORIG_REF_NAME==bd_6994_slot_3_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_21/bd_6994_slot_3_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_r_0 || ORIG_REF_NAME==bd_6994_slot_3_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_22/bd_6994_slot_4_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_aw_0 || ORIG_REF_NAME==bd_6994_slot_4_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_23/bd_6994_slot_4_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_w_0 || ORIG_REF_NAME==bd_6994_slot_4_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_24/bd_6994_slot_4_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_b_0 || ORIG_REF_NAME==bd_6994_slot_4_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_25/bd_6994_slot_4_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_ar_0 || ORIG_REF_NAME==bd_6994_slot_4_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_26/bd_6994_slot_4_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_r_0 || ORIG_REF_NAME==bd_6994_slot_4_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_27/bd_6994_slot_5_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_aw_0 || ORIG_REF_NAME==bd_6994_slot_5_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_28/bd_6994_slot_5_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_w_0 || ORIG_REF_NAME==bd_6994_slot_5_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_29/bd_6994_slot_5_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_b_0 || ORIG_REF_NAME==bd_6994_slot_5_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_30/bd_6994_slot_5_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_ar_0 || ORIG_REF_NAME==bd_6994_slot_5_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_31/bd_6994_slot_5_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_r_0 || ORIG_REF_NAME==bd_6994_slot_5_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_32/bd_6994_slot_6_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_aw_0 || ORIG_REF_NAME==bd_6994_slot_6_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_33/bd_6994_slot_6_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_w_0 || ORIG_REF_NAME==bd_6994_slot_6_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_34/bd_6994_slot_6_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_b_0 || ORIG_REF_NAME==bd_6994_slot_6_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_35/bd_6994_slot_6_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_ar_0 || ORIG_REF_NAME==bd_6994_slot_6_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_36/bd_6994_slot_6_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_r_0 || ORIG_REF_NAME==bd_6994_slot_6_r_0} -quiet] -quiet

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6994_ila_lib_0 || ORIG_REF_NAME==bd_6994_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6994_ila_lib_0 || ORIG_REF_NAME==bd_6994_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_0/bd_6994_ila_lib_0_ooc.xdc

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/bd_6994_ooc.xdc

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/pwm_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/pwm_system_ila_0_0.xci
# IP: The module: 'pwm_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/bd_6994.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994 || ORIG_REF_NAME==bd_6994} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_0/bd_6994_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_ila_lib_0 || ORIG_REF_NAME==bd_6994_ila_lib_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_1/bd_6994_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_g_inst_0 || ORIG_REF_NAME==bd_6994_g_inst_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_2/bd_6994_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_aw_0 || ORIG_REF_NAME==bd_6994_slot_0_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_3/bd_6994_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_w_0 || ORIG_REF_NAME==bd_6994_slot_0_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_4/bd_6994_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_b_0 || ORIG_REF_NAME==bd_6994_slot_0_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_5/bd_6994_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_ar_0 || ORIG_REF_NAME==bd_6994_slot_0_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_6/bd_6994_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_0_r_0 || ORIG_REF_NAME==bd_6994_slot_0_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_7/bd_6994_slot_1_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_aw_0 || ORIG_REF_NAME==bd_6994_slot_1_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_8/bd_6994_slot_1_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_w_0 || ORIG_REF_NAME==bd_6994_slot_1_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_9/bd_6994_slot_1_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_b_0 || ORIG_REF_NAME==bd_6994_slot_1_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_10/bd_6994_slot_1_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_ar_0 || ORIG_REF_NAME==bd_6994_slot_1_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_11/bd_6994_slot_1_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_1_r_0 || ORIG_REF_NAME==bd_6994_slot_1_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_12/bd_6994_slot_2_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_aw_0 || ORIG_REF_NAME==bd_6994_slot_2_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_13/bd_6994_slot_2_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_w_0 || ORIG_REF_NAME==bd_6994_slot_2_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_14/bd_6994_slot_2_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_b_0 || ORIG_REF_NAME==bd_6994_slot_2_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_15/bd_6994_slot_2_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_ar_0 || ORIG_REF_NAME==bd_6994_slot_2_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_16/bd_6994_slot_2_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_2_r_0 || ORIG_REF_NAME==bd_6994_slot_2_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_17/bd_6994_slot_3_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_aw_0 || ORIG_REF_NAME==bd_6994_slot_3_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_18/bd_6994_slot_3_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_w_0 || ORIG_REF_NAME==bd_6994_slot_3_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_19/bd_6994_slot_3_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_b_0 || ORIG_REF_NAME==bd_6994_slot_3_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_20/bd_6994_slot_3_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_ar_0 || ORIG_REF_NAME==bd_6994_slot_3_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_21/bd_6994_slot_3_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_3_r_0 || ORIG_REF_NAME==bd_6994_slot_3_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_22/bd_6994_slot_4_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_aw_0 || ORIG_REF_NAME==bd_6994_slot_4_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_23/bd_6994_slot_4_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_w_0 || ORIG_REF_NAME==bd_6994_slot_4_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_24/bd_6994_slot_4_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_b_0 || ORIG_REF_NAME==bd_6994_slot_4_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_25/bd_6994_slot_4_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_ar_0 || ORIG_REF_NAME==bd_6994_slot_4_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_26/bd_6994_slot_4_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_4_r_0 || ORIG_REF_NAME==bd_6994_slot_4_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_27/bd_6994_slot_5_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_aw_0 || ORIG_REF_NAME==bd_6994_slot_5_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_28/bd_6994_slot_5_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_w_0 || ORIG_REF_NAME==bd_6994_slot_5_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_29/bd_6994_slot_5_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_b_0 || ORIG_REF_NAME==bd_6994_slot_5_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_30/bd_6994_slot_5_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_ar_0 || ORIG_REF_NAME==bd_6994_slot_5_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_31/bd_6994_slot_5_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_5_r_0 || ORIG_REF_NAME==bd_6994_slot_5_r_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_32/bd_6994_slot_6_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_aw_0 || ORIG_REF_NAME==bd_6994_slot_6_aw_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_33/bd_6994_slot_6_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_w_0 || ORIG_REF_NAME==bd_6994_slot_6_w_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_34/bd_6994_slot_6_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_b_0 || ORIG_REF_NAME==bd_6994_slot_6_b_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_35/bd_6994_slot_6_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_ar_0 || ORIG_REF_NAME==bd_6994_slot_6_ar_0} -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_36/bd_6994_slot_6_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6994_slot_6_r_0 || ORIG_REF_NAME==bd_6994_slot_6_r_0} -quiet] -quiet

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6994_ila_lib_0 || ORIG_REF_NAME==bd_6994_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6994_ila_lib_0 || ORIG_REF_NAME==bd_6994_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/ip/ip_0/bd_6994_ila_lib_0_ooc.xdc

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/bd_0/bd_6994_ooc.xdc

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_system_ila_0_0/pwm_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
