// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "iiccomm.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic iiccomm::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic iiccomm::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> iiccomm::ap_ST_fsm_state1 = "1";
const sc_lv<10> iiccomm::ap_ST_fsm_state2 = "10";
const sc_lv<10> iiccomm::ap_ST_fsm_state3 = "100";
const sc_lv<10> iiccomm::ap_ST_fsm_state4 = "1000";
const sc_lv<10> iiccomm::ap_ST_fsm_state5 = "10000";
const sc_lv<10> iiccomm::ap_ST_fsm_state6 = "100000";
const sc_lv<10> iiccomm::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> iiccomm::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> iiccomm::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> iiccomm::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> iiccomm::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> iiccomm::ap_const_lv32_7 = "111";
const sc_lv<32> iiccomm::ap_const_lv32_1 = "1";
const sc_lv<32> iiccomm::ap_const_lv32_8 = "1000";
const int iiccomm::C_S_AXI_DATA_WIDTH = "100000";
const int iiccomm::C_M_AXI_IIC_TARGET_ADDR = "0000000000000000000000000000000000000000000000000000000000000000";
const int iiccomm::C_M_AXI_IIC_USER_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int iiccomm::C_M_AXI_IIC_PROT_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int iiccomm::C_M_AXI_IIC_CACHE_VALUE = "11";
const int iiccomm::C_M_AXI_DATA_WIDTH = "100000";
const sc_lv<64> iiccomm::ap_const_lv64_10000441 = "10000000000000000010001000001";
const sc_lv<64> iiccomm::ap_const_lv64_10000408 = "10000000000000000010000001000";
const sc_lv<1> iiccomm::ap_const_lv1_0 = "0";
const sc_lv<3> iiccomm::ap_const_lv3_0 = "000";
const sc_lv<2> iiccomm::ap_const_lv2_0 = "00";
const sc_lv<4> iiccomm::ap_const_lv4_0 = "0000";
const sc_lv<32> iiccomm::ap_const_lv32_9 = "1001";
const bool iiccomm::ap_const_boolean_1 = true;

iiccomm::iiccomm(sc_module_name name) : sc_module(name), mVcdFile(0) {
    iiccomm_AXILiteS_s_axi_U = new iiccomm_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("iiccomm_AXILiteS_s_axi_U");
    iiccomm_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    iiccomm_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    iiccomm_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    iiccomm_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    iiccomm_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    iiccomm_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    iiccomm_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    iiccomm_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    iiccomm_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    iiccomm_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    iiccomm_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    iiccomm_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    iiccomm_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    iiccomm_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    iiccomm_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    iiccomm_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    iiccomm_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    iiccomm_AXILiteS_s_axi_U->ACLK(ap_clk);
    iiccomm_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    iiccomm_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    iiccomm_AXILiteS_s_axi_U->ap_start(ap_start);
    iiccomm_AXILiteS_s_axi_U->interrupt(interrupt);
    iiccomm_AXILiteS_s_axi_U->ap_ready(ap_ready);
    iiccomm_AXILiteS_s_axi_U->ap_done(ap_done);
    iiccomm_AXILiteS_s_axi_U->ap_idle(ap_idle);
    iiccomm_AXILiteS_s_axi_U->outValue1_o(iic_addr_read_reg_114);
    iiccomm_AXILiteS_s_axi_U->outValue1_o_ap_vld(outValue1_o_ap_vld);
    iiccomm_AXILiteS_s_axi_U->outValue1_i(outValue1_i);
    iiccomm_AXILiteS_s_axi_U->outValue2_o(iic_addr_1_read_reg_119);
    iiccomm_AXILiteS_s_axi_U->outValue2_o_ap_vld(outValue2_o_ap_vld);
    iiccomm_AXILiteS_s_axi_U->outValue2_i(outValue2_i);
    iiccomm_iic_m_axi_U = new iiccomm_iic_m_axi<32,32,5,16,16,16,16,C_M_AXI_IIC_ID_WIDTH,C_M_AXI_IIC_ADDR_WIDTH,C_M_AXI_IIC_DATA_WIDTH,C_M_AXI_IIC_AWUSER_WIDTH,C_M_AXI_IIC_ARUSER_WIDTH,C_M_AXI_IIC_WUSER_WIDTH,C_M_AXI_IIC_RUSER_WIDTH,C_M_AXI_IIC_BUSER_WIDTH,C_M_AXI_IIC_TARGET_ADDR,C_M_AXI_IIC_USER_VALUE,C_M_AXI_IIC_PROT_VALUE,C_M_AXI_IIC_CACHE_VALUE>("iiccomm_iic_m_axi_U");
    iiccomm_iic_m_axi_U->AWVALID(m_axi_iic_AWVALID);
    iiccomm_iic_m_axi_U->AWREADY(m_axi_iic_AWREADY);
    iiccomm_iic_m_axi_U->AWADDR(m_axi_iic_AWADDR);
    iiccomm_iic_m_axi_U->AWID(m_axi_iic_AWID);
    iiccomm_iic_m_axi_U->AWLEN(m_axi_iic_AWLEN);
    iiccomm_iic_m_axi_U->AWSIZE(m_axi_iic_AWSIZE);
    iiccomm_iic_m_axi_U->AWBURST(m_axi_iic_AWBURST);
    iiccomm_iic_m_axi_U->AWLOCK(m_axi_iic_AWLOCK);
    iiccomm_iic_m_axi_U->AWCACHE(m_axi_iic_AWCACHE);
    iiccomm_iic_m_axi_U->AWPROT(m_axi_iic_AWPROT);
    iiccomm_iic_m_axi_U->AWQOS(m_axi_iic_AWQOS);
    iiccomm_iic_m_axi_U->AWREGION(m_axi_iic_AWREGION);
    iiccomm_iic_m_axi_U->AWUSER(m_axi_iic_AWUSER);
    iiccomm_iic_m_axi_U->WVALID(m_axi_iic_WVALID);
    iiccomm_iic_m_axi_U->WREADY(m_axi_iic_WREADY);
    iiccomm_iic_m_axi_U->WDATA(m_axi_iic_WDATA);
    iiccomm_iic_m_axi_U->WSTRB(m_axi_iic_WSTRB);
    iiccomm_iic_m_axi_U->WLAST(m_axi_iic_WLAST);
    iiccomm_iic_m_axi_U->WID(m_axi_iic_WID);
    iiccomm_iic_m_axi_U->WUSER(m_axi_iic_WUSER);
    iiccomm_iic_m_axi_U->ARVALID(m_axi_iic_ARVALID);
    iiccomm_iic_m_axi_U->ARREADY(m_axi_iic_ARREADY);
    iiccomm_iic_m_axi_U->ARADDR(m_axi_iic_ARADDR);
    iiccomm_iic_m_axi_U->ARID(m_axi_iic_ARID);
    iiccomm_iic_m_axi_U->ARLEN(m_axi_iic_ARLEN);
    iiccomm_iic_m_axi_U->ARSIZE(m_axi_iic_ARSIZE);
    iiccomm_iic_m_axi_U->ARBURST(m_axi_iic_ARBURST);
    iiccomm_iic_m_axi_U->ARLOCK(m_axi_iic_ARLOCK);
    iiccomm_iic_m_axi_U->ARCACHE(m_axi_iic_ARCACHE);
    iiccomm_iic_m_axi_U->ARPROT(m_axi_iic_ARPROT);
    iiccomm_iic_m_axi_U->ARQOS(m_axi_iic_ARQOS);
    iiccomm_iic_m_axi_U->ARREGION(m_axi_iic_ARREGION);
    iiccomm_iic_m_axi_U->ARUSER(m_axi_iic_ARUSER);
    iiccomm_iic_m_axi_U->RVALID(m_axi_iic_RVALID);
    iiccomm_iic_m_axi_U->RREADY(m_axi_iic_RREADY);
    iiccomm_iic_m_axi_U->RDATA(m_axi_iic_RDATA);
    iiccomm_iic_m_axi_U->RLAST(m_axi_iic_RLAST);
    iiccomm_iic_m_axi_U->RID(m_axi_iic_RID);
    iiccomm_iic_m_axi_U->RUSER(m_axi_iic_RUSER);
    iiccomm_iic_m_axi_U->RRESP(m_axi_iic_RRESP);
    iiccomm_iic_m_axi_U->BVALID(m_axi_iic_BVALID);
    iiccomm_iic_m_axi_U->BREADY(m_axi_iic_BREADY);
    iiccomm_iic_m_axi_U->BRESP(m_axi_iic_BRESP);
    iiccomm_iic_m_axi_U->BID(m_axi_iic_BID);
    iiccomm_iic_m_axi_U->BUSER(m_axi_iic_BUSER);
    iiccomm_iic_m_axi_U->ACLK(ap_clk);
    iiccomm_iic_m_axi_U->ARESET(ap_rst_n_inv);
    iiccomm_iic_m_axi_U->ACLK_EN(ap_var_for_const0);
    iiccomm_iic_m_axi_U->I_ARVALID(iic_ARVALID);
    iiccomm_iic_m_axi_U->I_ARREADY(iic_ARREADY);
    iiccomm_iic_m_axi_U->I_ARADDR(iic_ARADDR);
    iiccomm_iic_m_axi_U->I_ARID(ap_var_for_const1);
    iiccomm_iic_m_axi_U->I_ARLEN(ap_var_for_const2);
    iiccomm_iic_m_axi_U->I_ARSIZE(ap_var_for_const3);
    iiccomm_iic_m_axi_U->I_ARLOCK(ap_var_for_const4);
    iiccomm_iic_m_axi_U->I_ARCACHE(ap_var_for_const5);
    iiccomm_iic_m_axi_U->I_ARQOS(ap_var_for_const5);
    iiccomm_iic_m_axi_U->I_ARPROT(ap_var_for_const3);
    iiccomm_iic_m_axi_U->I_ARUSER(ap_var_for_const1);
    iiccomm_iic_m_axi_U->I_ARBURST(ap_var_for_const4);
    iiccomm_iic_m_axi_U->I_ARREGION(ap_var_for_const5);
    iiccomm_iic_m_axi_U->I_RVALID(iic_RVALID);
    iiccomm_iic_m_axi_U->I_RREADY(iic_RREADY);
    iiccomm_iic_m_axi_U->I_RDATA(iic_RDATA);
    iiccomm_iic_m_axi_U->I_RID(iic_RID);
    iiccomm_iic_m_axi_U->I_RUSER(iic_RUSER);
    iiccomm_iic_m_axi_U->I_RRESP(iic_RRESP);
    iiccomm_iic_m_axi_U->I_RLAST(iic_RLAST);
    iiccomm_iic_m_axi_U->I_AWVALID(ap_var_for_const6);
    iiccomm_iic_m_axi_U->I_AWREADY(iic_AWREADY);
    iiccomm_iic_m_axi_U->I_AWADDR(ap_var_for_const7);
    iiccomm_iic_m_axi_U->I_AWID(ap_var_for_const1);
    iiccomm_iic_m_axi_U->I_AWLEN(ap_var_for_const7);
    iiccomm_iic_m_axi_U->I_AWSIZE(ap_var_for_const3);
    iiccomm_iic_m_axi_U->I_AWLOCK(ap_var_for_const4);
    iiccomm_iic_m_axi_U->I_AWCACHE(ap_var_for_const5);
    iiccomm_iic_m_axi_U->I_AWQOS(ap_var_for_const5);
    iiccomm_iic_m_axi_U->I_AWPROT(ap_var_for_const3);
    iiccomm_iic_m_axi_U->I_AWUSER(ap_var_for_const1);
    iiccomm_iic_m_axi_U->I_AWBURST(ap_var_for_const4);
    iiccomm_iic_m_axi_U->I_AWREGION(ap_var_for_const5);
    iiccomm_iic_m_axi_U->I_WVALID(ap_var_for_const6);
    iiccomm_iic_m_axi_U->I_WREADY(iic_WREADY);
    iiccomm_iic_m_axi_U->I_WDATA(ap_var_for_const7);
    iiccomm_iic_m_axi_U->I_WID(ap_var_for_const1);
    iiccomm_iic_m_axi_U->I_WUSER(ap_var_for_const1);
    iiccomm_iic_m_axi_U->I_WLAST(ap_var_for_const6);
    iiccomm_iic_m_axi_U->I_WSTRB(ap_var_for_const5);
    iiccomm_iic_m_axi_U->I_BVALID(iic_BVALID);
    iiccomm_iic_m_axi_U->I_BREADY(ap_var_for_const6);
    iiccomm_iic_m_axi_U->I_BRESP(iic_BRESP);
    iiccomm_iic_m_axi_U->I_BID(iic_BID);
    iiccomm_iic_m_axi_U->I_BUSER(iic_BUSER);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_ioackin_iic_ARREADY);
    sensitive << ( iic_ARREADY );
    sensitive << ( ap_reg_ioackin_iic_ARREADY );

    SC_METHOD(thread_iic_ARADDR);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_reg_ioackin_iic_ARREADY );

    SC_METHOD(thread_iic_ARVALID);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_reg_ioackin_iic_ARREADY );

    SC_METHOD(thread_iic_RREADY);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( iic_RVALID );

    SC_METHOD(thread_iic_blk_n_AR);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_iic_ARREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_iic_blk_n_R);
    sensitive << ( m_axi_iic_RVALID );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_outValue1_o_ap_vld);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_outValue2_o_ap_vld);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( iic_RVALID );
    sensitive << ( ap_sig_ioackin_iic_ARREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const6);

    SC_THREAD(thread_ap_var_for_const7);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const5);

    ap_CS_fsm = "0000000001";
    ap_reg_ioackin_iic_ARREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "iiccomm_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, m_axi_iic_AWVALID, "(port)m_axi_iic_AWVALID");
    sc_trace(mVcdFile, m_axi_iic_AWREADY, "(port)m_axi_iic_AWREADY");
    sc_trace(mVcdFile, m_axi_iic_AWADDR, "(port)m_axi_iic_AWADDR");
    sc_trace(mVcdFile, m_axi_iic_AWID, "(port)m_axi_iic_AWID");
    sc_trace(mVcdFile, m_axi_iic_AWLEN, "(port)m_axi_iic_AWLEN");
    sc_trace(mVcdFile, m_axi_iic_AWSIZE, "(port)m_axi_iic_AWSIZE");
    sc_trace(mVcdFile, m_axi_iic_AWBURST, "(port)m_axi_iic_AWBURST");
    sc_trace(mVcdFile, m_axi_iic_AWLOCK, "(port)m_axi_iic_AWLOCK");
    sc_trace(mVcdFile, m_axi_iic_AWCACHE, "(port)m_axi_iic_AWCACHE");
    sc_trace(mVcdFile, m_axi_iic_AWPROT, "(port)m_axi_iic_AWPROT");
    sc_trace(mVcdFile, m_axi_iic_AWQOS, "(port)m_axi_iic_AWQOS");
    sc_trace(mVcdFile, m_axi_iic_AWREGION, "(port)m_axi_iic_AWREGION");
    sc_trace(mVcdFile, m_axi_iic_AWUSER, "(port)m_axi_iic_AWUSER");
    sc_trace(mVcdFile, m_axi_iic_WVALID, "(port)m_axi_iic_WVALID");
    sc_trace(mVcdFile, m_axi_iic_WREADY, "(port)m_axi_iic_WREADY");
    sc_trace(mVcdFile, m_axi_iic_WDATA, "(port)m_axi_iic_WDATA");
    sc_trace(mVcdFile, m_axi_iic_WSTRB, "(port)m_axi_iic_WSTRB");
    sc_trace(mVcdFile, m_axi_iic_WLAST, "(port)m_axi_iic_WLAST");
    sc_trace(mVcdFile, m_axi_iic_WID, "(port)m_axi_iic_WID");
    sc_trace(mVcdFile, m_axi_iic_WUSER, "(port)m_axi_iic_WUSER");
    sc_trace(mVcdFile, m_axi_iic_ARVALID, "(port)m_axi_iic_ARVALID");
    sc_trace(mVcdFile, m_axi_iic_ARREADY, "(port)m_axi_iic_ARREADY");
    sc_trace(mVcdFile, m_axi_iic_ARADDR, "(port)m_axi_iic_ARADDR");
    sc_trace(mVcdFile, m_axi_iic_ARID, "(port)m_axi_iic_ARID");
    sc_trace(mVcdFile, m_axi_iic_ARLEN, "(port)m_axi_iic_ARLEN");
    sc_trace(mVcdFile, m_axi_iic_ARSIZE, "(port)m_axi_iic_ARSIZE");
    sc_trace(mVcdFile, m_axi_iic_ARBURST, "(port)m_axi_iic_ARBURST");
    sc_trace(mVcdFile, m_axi_iic_ARLOCK, "(port)m_axi_iic_ARLOCK");
    sc_trace(mVcdFile, m_axi_iic_ARCACHE, "(port)m_axi_iic_ARCACHE");
    sc_trace(mVcdFile, m_axi_iic_ARPROT, "(port)m_axi_iic_ARPROT");
    sc_trace(mVcdFile, m_axi_iic_ARQOS, "(port)m_axi_iic_ARQOS");
    sc_trace(mVcdFile, m_axi_iic_ARREGION, "(port)m_axi_iic_ARREGION");
    sc_trace(mVcdFile, m_axi_iic_ARUSER, "(port)m_axi_iic_ARUSER");
    sc_trace(mVcdFile, m_axi_iic_RVALID, "(port)m_axi_iic_RVALID");
    sc_trace(mVcdFile, m_axi_iic_RREADY, "(port)m_axi_iic_RREADY");
    sc_trace(mVcdFile, m_axi_iic_RDATA, "(port)m_axi_iic_RDATA");
    sc_trace(mVcdFile, m_axi_iic_RLAST, "(port)m_axi_iic_RLAST");
    sc_trace(mVcdFile, m_axi_iic_RID, "(port)m_axi_iic_RID");
    sc_trace(mVcdFile, m_axi_iic_RUSER, "(port)m_axi_iic_RUSER");
    sc_trace(mVcdFile, m_axi_iic_RRESP, "(port)m_axi_iic_RRESP");
    sc_trace(mVcdFile, m_axi_iic_BVALID, "(port)m_axi_iic_BVALID");
    sc_trace(mVcdFile, m_axi_iic_BREADY, "(port)m_axi_iic_BREADY");
    sc_trace(mVcdFile, m_axi_iic_BRESP, "(port)m_axi_iic_BRESP");
    sc_trace(mVcdFile, m_axi_iic_BID, "(port)m_axi_iic_BID");
    sc_trace(mVcdFile, m_axi_iic_BUSER, "(port)m_axi_iic_BUSER");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, outValue1_i, "outValue1_i");
    sc_trace(mVcdFile, outValue1_o_ap_vld, "outValue1_o_ap_vld");
    sc_trace(mVcdFile, outValue2_i, "outValue2_i");
    sc_trace(mVcdFile, outValue2_o_ap_vld, "outValue2_o_ap_vld");
    sc_trace(mVcdFile, iic_blk_n_AR, "iic_blk_n_AR");
    sc_trace(mVcdFile, iic_blk_n_R, "iic_blk_n_R");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, iic_AWREADY, "iic_AWREADY");
    sc_trace(mVcdFile, iic_WREADY, "iic_WREADY");
    sc_trace(mVcdFile, iic_ARVALID, "iic_ARVALID");
    sc_trace(mVcdFile, iic_ARREADY, "iic_ARREADY");
    sc_trace(mVcdFile, iic_ARADDR, "iic_ARADDR");
    sc_trace(mVcdFile, iic_RVALID, "iic_RVALID");
    sc_trace(mVcdFile, iic_RREADY, "iic_RREADY");
    sc_trace(mVcdFile, iic_RDATA, "iic_RDATA");
    sc_trace(mVcdFile, iic_RLAST, "iic_RLAST");
    sc_trace(mVcdFile, iic_RID, "iic_RID");
    sc_trace(mVcdFile, iic_RUSER, "iic_RUSER");
    sc_trace(mVcdFile, iic_RRESP, "iic_RRESP");
    sc_trace(mVcdFile, iic_BVALID, "iic_BVALID");
    sc_trace(mVcdFile, iic_BRESP, "iic_BRESP");
    sc_trace(mVcdFile, iic_BID, "iic_BID");
    sc_trace(mVcdFile, iic_BUSER, "iic_BUSER");
    sc_trace(mVcdFile, ap_sig_ioackin_iic_ARREADY, "ap_sig_ioackin_iic_ARREADY");
    sc_trace(mVcdFile, iic_addr_read_reg_114, "iic_addr_read_reg_114");
    sc_trace(mVcdFile, iic_addr_1_read_reg_119, "iic_addr_1_read_reg_119");
    sc_trace(mVcdFile, ap_reg_ioackin_iic_ARREADY, "ap_reg_ioackin_iic_ARREADY");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("iiccomm.hdltvin.dat");
    mHdltvoutHandle.open("iiccomm.hdltvout.dat");
}

iiccomm::~iiccomm() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete iiccomm_AXILiteS_s_axi_U;
    delete iiccomm_iic_m_axi_U;
}

void iiccomm::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void iiccomm::thread_ap_var_for_const6() {
    ap_var_for_const6 = ap_const_logic_0;
}

void iiccomm::thread_ap_var_for_const7() {
    ap_var_for_const7 = ap_const_lv32_0;
}

void iiccomm::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv32_1;
}

void iiccomm::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void iiccomm::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv3_0;
}

void iiccomm::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv2_0;
}

void iiccomm::thread_ap_var_for_const5() {
    ap_var_for_const5 = ap_const_lv4_0;
}

void iiccomm::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_iic_ARREADY = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
              !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_iic_ARREADY.read()))) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
              esl_seteq<1,1,1>(ap_sig_ioackin_iic_ARREADY.read(), ap_const_logic_1)))) {
            ap_reg_ioackin_iic_ARREADY = ap_const_logic_0;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                     esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, iic_ARREADY.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, iic_ARREADY.read())))) {
            ap_reg_ioackin_iic_ARREADY = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(iic_RVALID.read(), ap_const_logic_1))) {
        iic_addr_1_read_reg_119 = iic_RDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(iic_RVALID.read(), ap_const_logic_1))) {
        iic_addr_read_reg_114 = iic_RDATA.read();
    }
}

void iiccomm::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void iiccomm::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void iiccomm::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void iiccomm::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void iiccomm::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void iiccomm::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void iiccomm::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void iiccomm::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void iiccomm::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void iiccomm::thread_ap_sig_ioackin_iic_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_iic_ARREADY.read())) {
        ap_sig_ioackin_iic_ARREADY = iic_ARREADY.read();
    } else {
        ap_sig_ioackin_iic_ARREADY = ap_const_logic_1;
    }
}

void iiccomm::thread_iic_ARADDR() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_iic_ARREADY.read())) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            iic_ARADDR =  (sc_lv<32>) (ap_const_lv64_10000408);
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            iic_ARADDR =  (sc_lv<32>) (ap_const_lv64_10000441);
        } else {
            iic_ARADDR = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        iic_ARADDR = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void iiccomm::thread_iic_ARVALID() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_iic_ARREADY.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_iic_ARREADY.read())))) {
        iic_ARVALID = ap_const_logic_1;
    } else {
        iic_ARVALID = ap_const_logic_0;
    }
}

void iiccomm::thread_iic_RREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(iic_RVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(iic_RVALID.read(), ap_const_logic_1)))) {
        iic_RREADY = ap_const_logic_1;
    } else {
        iic_RREADY = ap_const_logic_0;
    }
}

void iiccomm::thread_iic_blk_n_AR() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        iic_blk_n_AR = m_axi_iic_ARREADY.read();
    } else {
        iic_blk_n_AR = ap_const_logic_1;
    }
}

void iiccomm::thread_iic_blk_n_R() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        iic_blk_n_R = m_axi_iic_RVALID.read();
    } else {
        iic_blk_n_R = ap_const_logic_1;
    }
}

void iiccomm::thread_outValue1_o_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        outValue1_o_ap_vld = ap_const_logic_1;
    } else {
        outValue1_o_ap_vld = ap_const_logic_0;
    }
}

void iiccomm::thread_outValue2_o_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        outValue2_o_ap_vld = ap_const_logic_1;
    } else {
        outValue2_o_ap_vld = ap_const_logic_0;
    }
}

void iiccomm::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_iic_ARREADY.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_iic_ARREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(iic_RVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(iic_RVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<10>) ("XXXXXXXXXX");
            break;
    }
}

void iiccomm::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"m_axi_iic_AWVALID\" :  \"" << m_axi_iic_AWVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_AWREADY\" :  \"" << m_axi_iic_AWREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWADDR\" :  \"" << m_axi_iic_AWADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWID\" :  \"" << m_axi_iic_AWID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWLEN\" :  \"" << m_axi_iic_AWLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWSIZE\" :  \"" << m_axi_iic_AWSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWBURST\" :  \"" << m_axi_iic_AWBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWLOCK\" :  \"" << m_axi_iic_AWLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWCACHE\" :  \"" << m_axi_iic_AWCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWPROT\" :  \"" << m_axi_iic_AWPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWQOS\" :  \"" << m_axi_iic_AWQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWREGION\" :  \"" << m_axi_iic_AWREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_AWUSER\" :  \"" << m_axi_iic_AWUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_WVALID\" :  \"" << m_axi_iic_WVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_WREADY\" :  \"" << m_axi_iic_WREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_WDATA\" :  \"" << m_axi_iic_WDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_WSTRB\" :  \"" << m_axi_iic_WSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_WLAST\" :  \"" << m_axi_iic_WLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_WID\" :  \"" << m_axi_iic_WID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_WUSER\" :  \"" << m_axi_iic_WUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARVALID\" :  \"" << m_axi_iic_ARVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_ARREADY\" :  \"" << m_axi_iic_ARREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARADDR\" :  \"" << m_axi_iic_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARID\" :  \"" << m_axi_iic_ARID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARLEN\" :  \"" << m_axi_iic_ARLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARSIZE\" :  \"" << m_axi_iic_ARSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARBURST\" :  \"" << m_axi_iic_ARBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARLOCK\" :  \"" << m_axi_iic_ARLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARCACHE\" :  \"" << m_axi_iic_ARCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARPROT\" :  \"" << m_axi_iic_ARPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARQOS\" :  \"" << m_axi_iic_ARQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARREGION\" :  \"" << m_axi_iic_ARREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_ARUSER\" :  \"" << m_axi_iic_ARUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_RVALID\" :  \"" << m_axi_iic_RVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_RREADY\" :  \"" << m_axi_iic_RREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_RDATA\" :  \"" << m_axi_iic_RDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_RLAST\" :  \"" << m_axi_iic_RLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_RID\" :  \"" << m_axi_iic_RID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_RUSER\" :  \"" << m_axi_iic_RUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_RRESP\" :  \"" << m_axi_iic_RRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_BVALID\" :  \"" << m_axi_iic_BVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_iic_BREADY\" :  \"" << m_axi_iic_BREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_BRESP\" :  \"" << m_axi_iic_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_BID\" :  \"" << m_axi_iic_BID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_iic_BUSER\" :  \"" << m_axi_iic_BUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

