// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_normalizer (
unsigned int regs_in[6],
unsigned int min_high,
unsigned int max_high,
ap_fixed<16, 1, (ap_q_mode) 5, (ap_o_mode)3, 0> m[6]);
