# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_pwm_0_2/pwm_pwm_0_2.xci
# IP: The module: 'pwm_pwm_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_pwm_0_2/constraints/pwm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_pwm_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_pwm_0_2/pwm_pwm_0_2.xci
# IP: The module: 'pwm_pwm_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/brennan/Documents/pynq-copter/pynqcopter/pwm/pwm/pwm.srcs/sources_1/bd/pwm/ip/pwm_pwm_0_2/constraints/pwm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pwm_pwm_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
