# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/iavendano/pynq-copter/pynqcopter/iicComm5/design.xdc

# Block Designs: bd/iicComm5/iicComm5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5 || ORIG_REF_NAME==iicComm5} -quiet] -quiet

# IP: bd/iicComm5/ip/iicComm5_axi_iic_0_0/iicComm5_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5_axi_iic_0_0 || ORIG_REF_NAME==iicComm5_axi_iic_0_0} -quiet] -quiet

# IP: bd/iicComm5/ip/iicComm5_iiccomm5_0_0/iicComm5_iiccomm5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5_iiccomm5_0_0 || ORIG_REF_NAME==iicComm5_iiccomm5_0_0} -quiet] -quiet

# IP: bd/iicComm5/ip/iicComm5_processing_system7_0_0/iicComm5_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5_processing_system7_0_0 || ORIG_REF_NAME==iicComm5_processing_system7_0_0} -quiet] -quiet

# IP: bd/iicComm5/ip/iicComm5_ps7_0_axi_periph_0/iicComm5_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5_ps7_0_axi_periph_0 || ORIG_REF_NAME==iicComm5_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/iicComm5/ip/iicComm5_rst_ps7_0_100M_0/iicComm5_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5_rst_ps7_0_100M_0 || ORIG_REF_NAME==iicComm5_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/iicComm5/ip/iicComm5_xbar_0/iicComm5_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5_xbar_0 || ORIG_REF_NAME==iicComm5_xbar_0} -quiet] -quiet

# IP: bd/iicComm5/ip/iicComm5_s01_mmu_0/iicComm5_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5_s01_mmu_0 || ORIG_REF_NAME==iicComm5_s01_mmu_0} -quiet] -quiet

# IP: bd/iicComm5/ip/iicComm5_auto_pc_1/iicComm5_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5_auto_pc_1 || ORIG_REF_NAME==iicComm5_auto_pc_1} -quiet] -quiet

# IP: bd/iicComm5/ip/iicComm5_auto_pc_0/iicComm5_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm5_auto_pc_0 || ORIG_REF_NAME==iicComm5_auto_pc_0} -quiet] -quiet

# XDC: bd/iicComm5/iicComm5_ooc.xdc
