set_property SRC_FILE_INFO {cfile:/home/iavendano/pynq-copter/pynqcopter/iicComm3/design.xdc rfile:../../../../design.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {pb_i[0]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports {pb_i[1]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {pb_i[2]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {pb_i[3]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports {led_o[0]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {led_o[1]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports {led_o[2]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {led_o[3]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[0]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[1]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[2]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[3]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[4]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[5]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[6]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[7]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[8]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[9]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[10]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[11]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[12]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[13]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[14]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[15]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W11 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[16]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[17]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T5  IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[18]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U10 IOSTANDARD LVCMOS33} [get_ports {arduino_gpio_tri_io[19]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports arduino_iic_scl_io]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports arduino_iic_sda_io]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {arduino_gpio_tri_io[*]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {pmodJA_gpio_tri_io[1]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {pmodJA_gpio_tri_io[0]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {pmodJA_gpio_tri_io[3]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {pmodJA_gpio_tri_io[2]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {pmodJA_gpio_tri_io[5]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {pmodJA_gpio_tri_io[4]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {pmodJA_gpio_tri_io[7]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {pmodJA_gpio_tri_io[6]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {pmodJA_gpio_tri_io[2]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {pmodJA_gpio_tri_io[3]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {pmodJA_gpio_tri_io[6]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {pmodJA_gpio_tri_io[7]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports {pmodJB_gpio_tri_io[1]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {pmodJB_gpio_tri_io[0]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {pmodJB_gpio_tri_io[3]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {pmodJB_gpio_tri_io[2]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports {pmodJB_gpio_tri_io[5]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {pmodJB_gpio_tri_io[4]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports {pmodJB_gpio_tri_io[7]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports {pmodJB_gpio_tri_io[6]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {pmodJB_gpio_tri_io[2]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {pmodJB_gpio_tri_io[3]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {pmodJB_gpio_tri_io[6]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports {pmodJB_gpio_tri_io[7]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list iicComm3_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[0]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[1]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[2]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[3]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[4]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[5]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[6]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[7]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[8]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[9]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[10]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[11]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[12]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[13]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[14]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[15]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[16]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[17]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[18]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[19]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[20]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[21]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[22]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[23]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[24]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[25]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[26]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[27]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[28]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[29]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[30]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_ARADDR[31]}]]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[0]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[1]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[2]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[3]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[4]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[5]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[6]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[7]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[8]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[9]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[10]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[11]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[12]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[13]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[14]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[15]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[16]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[17]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[18]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[19]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[20]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[21]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[22]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[23]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[24]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[25]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[26]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[27]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[28]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[29]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[30]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WDATA[31]}]]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {iicComm3_i/ps7_0_axi_periph_M01_AXI_WSTRB[0]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WSTRB[1]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WSTRB[2]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_WSTRB[3]}]]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {iicComm3_i/ps7_0_axi_periph_M01_AXI_RRESP[0]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RRESP[1]}]]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[0]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[1]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[2]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[3]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[4]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[5]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[6]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[7]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[8]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[9]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[10]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[11]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[12]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[13]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[14]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[15]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[16]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[17]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[18]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[19]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[20]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[21]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[22]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[23]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[24]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[25]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[26]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[27]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[28]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[29]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[30]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_RDATA[31]}]]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[0]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[1]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[2]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[3]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[4]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[5]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[6]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[7]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[8]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[9]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[10]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[11]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[12]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[13]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[14]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[15]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[16]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[17]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[18]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[19]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[20]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[21]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[22]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[23]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[24]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[25]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[26]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[27]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[28]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[29]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[30]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_AWADDR[31]}]]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {iicComm3_i/ps7_0_axi_periph_M01_AXI_BRESP[0]} {iicComm3_i/ps7_0_axi_periph_M01_AXI_BRESP[1]}]]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_ARREADY]]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_ARVALID]]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_AWREADY]]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_AWVALID]]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_BREADY]]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_BVALID]]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_RREADY]]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_RVALID]]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_WREADY]]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list iicComm3_i/ps7_0_axi_periph_M01_AXI_WVALID]]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
