// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xiiccomm3.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XIiccomm3_CfgInitialize(XIiccomm3 *InstancePtr, XIiccomm3_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Outvalue_first_BaseAddress = ConfigPtr->Outvalue_first_BaseAddress;
    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XIiccomm3_Start(XIiccomm3 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIiccomm3_ReadReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_AP_CTRL) & 0x80;
    XIiccomm3_WriteReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XIiccomm3_IsDone(XIiccomm3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIiccomm3_ReadReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XIiccomm3_IsIdle(XIiccomm3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIiccomm3_ReadReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XIiccomm3_IsReady(XIiccomm3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIiccomm3_ReadReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XIiccomm3_EnableAutoRestart(XIiccomm3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIiccomm3_WriteReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XIiccomm3_DisableAutoRestart(XIiccomm3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIiccomm3_WriteReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XIiccomm3_Get_outValue(XIiccomm3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIiccomm3_ReadReg(InstancePtr->Outvalue_first_BaseAddress, XIICCOMM3_OUTVALUE_FIRST_ADDR_OUTVALUE_DATA);
    return Data;
}

u32 XIiccomm3_Get_outValue_vld(XIiccomm3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIiccomm3_ReadReg(InstancePtr->Outvalue_first_BaseAddress, XIICCOMM3_OUTVALUE_FIRST_ADDR_OUTVALUE_CTRL);
    return Data & 0x1;
}

void XIiccomm3_InterruptGlobalEnable(XIiccomm3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIiccomm3_WriteReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_GIE, 1);
}

void XIiccomm3_InterruptGlobalDisable(XIiccomm3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIiccomm3_WriteReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_GIE, 0);
}

void XIiccomm3_InterruptEnable(XIiccomm3 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XIiccomm3_ReadReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_IER);
    XIiccomm3_WriteReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_IER, Register | Mask);
}

void XIiccomm3_InterruptDisable(XIiccomm3 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XIiccomm3_ReadReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_IER);
    XIiccomm3_WriteReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_IER, Register & (~Mask));
}

void XIiccomm3_InterruptClear(XIiccomm3 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIiccomm3_WriteReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_ISR, Mask);
}

u32 XIiccomm3_InterruptGetEnabled(XIiccomm3 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XIiccomm3_ReadReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_IER);
}

u32 XIiccomm3_InterruptGetStatus(XIiccomm3 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XIiccomm3_ReadReg(InstancePtr->Axilites_BaseAddress, XIICCOMM3_AXILITES_ADDR_ISR);
}

