// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XIICCOMM2_H
#define XIICCOMM2_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xiiccomm2_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XIiccomm2_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XIiccomm2;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XIiccomm2_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XIiccomm2_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XIiccomm2_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XIiccomm2_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XIiccomm2_Initialize(XIiccomm2 *InstancePtr, u16 DeviceId);
XIiccomm2_Config* XIiccomm2_LookupConfig(u16 DeviceId);
int XIiccomm2_CfgInitialize(XIiccomm2 *InstancePtr, XIiccomm2_Config *ConfigPtr);
#else
int XIiccomm2_Initialize(XIiccomm2 *InstancePtr, const char* InstanceName);
int XIiccomm2_Release(XIiccomm2 *InstancePtr);
#endif

void XIiccomm2_Start(XIiccomm2 *InstancePtr);
u32 XIiccomm2_IsDone(XIiccomm2 *InstancePtr);
u32 XIiccomm2_IsIdle(XIiccomm2 *InstancePtr);
u32 XIiccomm2_IsReady(XIiccomm2 *InstancePtr);
void XIiccomm2_EnableAutoRestart(XIiccomm2 *InstancePtr);
void XIiccomm2_DisableAutoRestart(XIiccomm2 *InstancePtr);

u32 XIiccomm2_Get_stat_reg_outValue1_V(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_stat_reg_outValue1_V_vld(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_stat_reg_outValue2_V(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_stat_reg_outValue2_V_vld(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_stat_reg_outValue3_V(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_stat_reg_outValue3_V_vld(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_stat_reg_outValue4_V(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_stat_reg_outValue4_V_vld(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_ctrl_reg_outValue_V(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_ctrl_reg_outValue_V_vld(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_empty_pirq_outValue_V(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_empty_pirq_outValue_V_vld(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_full_pirq_outValue_V(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_full_pirq_outValue_V_vld(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_tx_fifo_outValue_V(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_tx_fifo_outValue_V_vld(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_rx_fifo_outValue_V(XIiccomm2 *InstancePtr);
u32 XIiccomm2_Get_rx_fifo_outValue_V_vld(XIiccomm2 *InstancePtr);

void XIiccomm2_InterruptGlobalEnable(XIiccomm2 *InstancePtr);
void XIiccomm2_InterruptGlobalDisable(XIiccomm2 *InstancePtr);
void XIiccomm2_InterruptEnable(XIiccomm2 *InstancePtr, u32 Mask);
void XIiccomm2_InterruptDisable(XIiccomm2 *InstancePtr, u32 Mask);
void XIiccomm2_InterruptClear(XIiccomm2 *InstancePtr, u32 Mask);
u32 XIiccomm2_InterruptGetEnabled(XIiccomm2 *InstancePtr);
u32 XIiccomm2_InterruptGetStatus(XIiccomm2 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
