# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/iavendano/pynq-copter/pynqcopter/iicComm2Update/design.xdc

# Block Designs: bd/iicComm2Update/iicComm2Update.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update || ORIG_REF_NAME==iicComm2Update} -quiet] -quiet

# IP: bd/iicComm2Update/ip/iicComm2Update_axi_iic_0_0/iicComm2Update_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update_axi_iic_0_0 || ORIG_REF_NAME==iicComm2Update_axi_iic_0_0} -quiet] -quiet

# IP: bd/iicComm2Update/ip/iicComm2Update_iiccomm2update_0_0/iicComm2Update_iiccomm2update_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update_iiccomm2update_0_0 || ORIG_REF_NAME==iicComm2Update_iiccomm2update_0_0} -quiet] -quiet

# IP: bd/iicComm2Update/ip/iicComm2Update_processing_system7_0_0/iicComm2Update_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update_processing_system7_0_0 || ORIG_REF_NAME==iicComm2Update_processing_system7_0_0} -quiet] -quiet

# IP: bd/iicComm2Update/ip/iicComm2Update_ps7_0_axi_periph_0/iicComm2Update_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update_ps7_0_axi_periph_0 || ORIG_REF_NAME==iicComm2Update_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/iicComm2Update/ip/iicComm2Update_rst_ps7_0_100M_0/iicComm2Update_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update_rst_ps7_0_100M_0 || ORIG_REF_NAME==iicComm2Update_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/iicComm2Update/ip/iicComm2Update_xbar_0/iicComm2Update_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update_xbar_0 || ORIG_REF_NAME==iicComm2Update_xbar_0} -quiet] -quiet

# IP: bd/iicComm2Update/ip/iicComm2Update_s01_mmu_0/iicComm2Update_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update_s01_mmu_0 || ORIG_REF_NAME==iicComm2Update_s01_mmu_0} -quiet] -quiet

# IP: bd/iicComm2Update/ip/iicComm2Update_auto_pc_1/iicComm2Update_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update_auto_pc_1 || ORIG_REF_NAME==iicComm2Update_auto_pc_1} -quiet] -quiet

# IP: bd/iicComm2Update/ip/iicComm2Update_auto_pc_0/iicComm2Update_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iicComm2Update_auto_pc_0 || ORIG_REF_NAME==iicComm2Update_auto_pc_0} -quiet] -quiet

# XDC: bd/iicComm2Update/iicComm2Update_ooc.xdc
