// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="iiccomm3,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.500000,HLS_SYN_LAT=38,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1153,HLS_SYN_LUT=1708}" *)

module iiccomm3 (
        ap_clk,
        ap_rst_n,
        m_axi_iic_V_AWVALID,
        m_axi_iic_V_AWREADY,
        m_axi_iic_V_AWADDR,
        m_axi_iic_V_AWID,
        m_axi_iic_V_AWLEN,
        m_axi_iic_V_AWSIZE,
        m_axi_iic_V_AWBURST,
        m_axi_iic_V_AWLOCK,
        m_axi_iic_V_AWCACHE,
        m_axi_iic_V_AWPROT,
        m_axi_iic_V_AWQOS,
        m_axi_iic_V_AWREGION,
        m_axi_iic_V_AWUSER,
        m_axi_iic_V_WVALID,
        m_axi_iic_V_WREADY,
        m_axi_iic_V_WDATA,
        m_axi_iic_V_WSTRB,
        m_axi_iic_V_WLAST,
        m_axi_iic_V_WID,
        m_axi_iic_V_WUSER,
        m_axi_iic_V_ARVALID,
        m_axi_iic_V_ARREADY,
        m_axi_iic_V_ARADDR,
        m_axi_iic_V_ARID,
        m_axi_iic_V_ARLEN,
        m_axi_iic_V_ARSIZE,
        m_axi_iic_V_ARBURST,
        m_axi_iic_V_ARLOCK,
        m_axi_iic_V_ARCACHE,
        m_axi_iic_V_ARPROT,
        m_axi_iic_V_ARQOS,
        m_axi_iic_V_ARREGION,
        m_axi_iic_V_ARUSER,
        m_axi_iic_V_RVALID,
        m_axi_iic_V_RREADY,
        m_axi_iic_V_RDATA,
        m_axi_iic_V_RLAST,
        m_axi_iic_V_RID,
        m_axi_iic_V_RUSER,
        m_axi_iic_V_RRESP,
        m_axi_iic_V_BVALID,
        m_axi_iic_V_BREADY,
        m_axi_iic_V_BRESP,
        m_axi_iic_V_BID,
        m_axi_iic_V_BUSER,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 39'd1;
parameter    ap_ST_fsm_state2 = 39'd2;
parameter    ap_ST_fsm_state3 = 39'd4;
parameter    ap_ST_fsm_state4 = 39'd8;
parameter    ap_ST_fsm_state5 = 39'd16;
parameter    ap_ST_fsm_state6 = 39'd32;
parameter    ap_ST_fsm_state7 = 39'd64;
parameter    ap_ST_fsm_state8 = 39'd128;
parameter    ap_ST_fsm_state9 = 39'd256;
parameter    ap_ST_fsm_state10 = 39'd512;
parameter    ap_ST_fsm_state11 = 39'd1024;
parameter    ap_ST_fsm_state12 = 39'd2048;
parameter    ap_ST_fsm_state13 = 39'd4096;
parameter    ap_ST_fsm_state14 = 39'd8192;
parameter    ap_ST_fsm_state15 = 39'd16384;
parameter    ap_ST_fsm_state16 = 39'd32768;
parameter    ap_ST_fsm_state17 = 39'd65536;
parameter    ap_ST_fsm_state18 = 39'd131072;
parameter    ap_ST_fsm_state19 = 39'd262144;
parameter    ap_ST_fsm_state20 = 39'd524288;
parameter    ap_ST_fsm_state21 = 39'd1048576;
parameter    ap_ST_fsm_state22 = 39'd2097152;
parameter    ap_ST_fsm_state23 = 39'd4194304;
parameter    ap_ST_fsm_state24 = 39'd8388608;
parameter    ap_ST_fsm_state25 = 39'd16777216;
parameter    ap_ST_fsm_state26 = 39'd33554432;
parameter    ap_ST_fsm_state27 = 39'd67108864;
parameter    ap_ST_fsm_state28 = 39'd134217728;
parameter    ap_ST_fsm_state29 = 39'd268435456;
parameter    ap_ST_fsm_state30 = 39'd536870912;
parameter    ap_ST_fsm_state31 = 39'd1073741824;
parameter    ap_ST_fsm_state32 = 39'd2147483648;
parameter    ap_ST_fsm_state33 = 39'd4294967296;
parameter    ap_ST_fsm_state34 = 39'd8589934592;
parameter    ap_ST_fsm_state35 = 39'd17179869184;
parameter    ap_ST_fsm_state36 = 39'd34359738368;
parameter    ap_ST_fsm_state37 = 39'd68719476736;
parameter    ap_ST_fsm_state38 = 39'd137438953472;
parameter    ap_ST_fsm_state39 = 39'd274877906944;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_IIC_V_ID_WIDTH = 1;
parameter    C_M_AXI_IIC_V_ADDR_WIDTH = 32;
parameter    C_M_AXI_IIC_V_DATA_WIDTH = 32;
parameter    C_M_AXI_IIC_V_AWUSER_WIDTH = 1;
parameter    C_M_AXI_IIC_V_ARUSER_WIDTH = 1;
parameter    C_M_AXI_IIC_V_WUSER_WIDTH = 1;
parameter    C_M_AXI_IIC_V_RUSER_WIDTH = 1;
parameter    C_M_AXI_IIC_V_BUSER_WIDTH = 1;
parameter    C_M_AXI_IIC_V_TARGET_ADDR = 0;
parameter    C_M_AXI_IIC_V_USER_VALUE = 0;
parameter    C_M_AXI_IIC_V_PROT_VALUE = 0;
parameter    C_M_AXI_IIC_V_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_IIC_V_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_iic_V_AWVALID;
input   m_axi_iic_V_AWREADY;
output  [C_M_AXI_IIC_V_ADDR_WIDTH - 1:0] m_axi_iic_V_AWADDR;
output  [C_M_AXI_IIC_V_ID_WIDTH - 1:0] m_axi_iic_V_AWID;
output  [7:0] m_axi_iic_V_AWLEN;
output  [2:0] m_axi_iic_V_AWSIZE;
output  [1:0] m_axi_iic_V_AWBURST;
output  [1:0] m_axi_iic_V_AWLOCK;
output  [3:0] m_axi_iic_V_AWCACHE;
output  [2:0] m_axi_iic_V_AWPROT;
output  [3:0] m_axi_iic_V_AWQOS;
output  [3:0] m_axi_iic_V_AWREGION;
output  [C_M_AXI_IIC_V_AWUSER_WIDTH - 1:0] m_axi_iic_V_AWUSER;
output   m_axi_iic_V_WVALID;
input   m_axi_iic_V_WREADY;
output  [C_M_AXI_IIC_V_DATA_WIDTH - 1:0] m_axi_iic_V_WDATA;
output  [C_M_AXI_IIC_V_WSTRB_WIDTH - 1:0] m_axi_iic_V_WSTRB;
output   m_axi_iic_V_WLAST;
output  [C_M_AXI_IIC_V_ID_WIDTH - 1:0] m_axi_iic_V_WID;
output  [C_M_AXI_IIC_V_WUSER_WIDTH - 1:0] m_axi_iic_V_WUSER;
output   m_axi_iic_V_ARVALID;
input   m_axi_iic_V_ARREADY;
output  [C_M_AXI_IIC_V_ADDR_WIDTH - 1:0] m_axi_iic_V_ARADDR;
output  [C_M_AXI_IIC_V_ID_WIDTH - 1:0] m_axi_iic_V_ARID;
output  [7:0] m_axi_iic_V_ARLEN;
output  [2:0] m_axi_iic_V_ARSIZE;
output  [1:0] m_axi_iic_V_ARBURST;
output  [1:0] m_axi_iic_V_ARLOCK;
output  [3:0] m_axi_iic_V_ARCACHE;
output  [2:0] m_axi_iic_V_ARPROT;
output  [3:0] m_axi_iic_V_ARQOS;
output  [3:0] m_axi_iic_V_ARREGION;
output  [C_M_AXI_IIC_V_ARUSER_WIDTH - 1:0] m_axi_iic_V_ARUSER;
input   m_axi_iic_V_RVALID;
output   m_axi_iic_V_RREADY;
input  [C_M_AXI_IIC_V_DATA_WIDTH - 1:0] m_axi_iic_V_RDATA;
input   m_axi_iic_V_RLAST;
input  [C_M_AXI_IIC_V_ID_WIDTH - 1:0] m_axi_iic_V_RID;
input  [C_M_AXI_IIC_V_RUSER_WIDTH - 1:0] m_axi_iic_V_RUSER;
input  [1:0] m_axi_iic_V_RRESP;
input   m_axi_iic_V_BVALID;
output   m_axi_iic_V_BREADY;
input  [1:0] m_axi_iic_V_BRESP;
input  [C_M_AXI_IIC_V_ID_WIDTH - 1:0] m_axi_iic_V_BID;
input  [C_M_AXI_IIC_V_BUSER_WIDTH - 1:0] m_axi_iic_V_BUSER;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [38:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg    stat_reg_outValue1_V_ap_vld;
reg    stat_reg_outValue2_V_ap_vld;
reg    stat_reg_outValue3_V_ap_vld;
reg    stat_reg_outValue4_V_ap_vld;
reg    ctrl_reg_outValue_V_ap_vld;
reg    empty_pirq_outValue_V_ap_vld;
reg    full_pirq_outValue_V_ap_vld;
reg    tx_fifo_outValue1_V_ap_vld;
reg    tx_fifo_outValue2_V_ap_vld;
reg    tx_fifo_outValue3_V_ap_vld;
reg    rx_fifo_outValue_V_ap_vld;
reg    length1_V_ap_vld;
reg    iic_V_blk_n_AR;
reg    iic_V_blk_n_R;
wire    ap_CS_fsm_state8;
reg    iic_V_blk_n_AW;
wire    ap_CS_fsm_state9;
reg    iic_V_blk_n_W;
wire    ap_CS_fsm_state10;
reg    iic_V_blk_n_B;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state38;
reg    iic_V_AWVALID;
wire    iic_V_AWREADY;
reg   [31:0] iic_V_AWADDR;
reg    iic_V_WVALID;
wire    iic_V_WREADY;
reg   [31:0] iic_V_WDATA;
reg    iic_V_ARVALID;
wire    iic_V_ARREADY;
reg   [31:0] iic_V_ARADDR;
wire    iic_V_RVALID;
reg    iic_V_RREADY;
wire   [31:0] iic_V_RDATA;
wire    iic_V_RLAST;
wire   [0:0] iic_V_RID;
wire   [0:0] iic_V_RUSER;
wire   [1:0] iic_V_RRESP;
wire    iic_V_BVALID;
reg    iic_V_BREADY;
wire   [1:0] iic_V_BRESP;
wire   [0:0] iic_V_BID;
wire   [0:0] iic_V_BUSER;
reg    ap_sig_ioackin_iic_V_ARREADY;
reg   [31:0] iic_V_addr_read_reg_295;
reg    ap_sig_ioackin_iic_V_WREADY;
reg    ap_sig_ioackin_iic_V_AWREADY;
reg    ap_block_state10_io;
reg   [31:0] iic_V_addr_2_read_reg_312;
reg   [31:0] iic_V_addr_4_read_reg_332;
reg    ap_reg_ioackin_iic_V_ARREADY;
reg    ap_reg_ioackin_iic_V_AWREADY;
reg    ap_reg_ioackin_iic_V_WREADY;
reg    ap_reg_ioackin_empty_pirq_outValue_V_dummy_ack;
reg    ap_reg_ioackin_length1_V_dummy_ack;
reg    ap_reg_ioackin_full_pirq_outValue_V_dummy_ack;
reg    ap_reg_ioackin_ctrl_reg_outValue_V_dummy_ack;
reg    ap_reg_ioackin_tx_fifo_outValue1_V_dummy_ack;
reg    ap_reg_ioackin_tx_fifo_outValue2_V_dummy_ack;
reg    ap_reg_ioackin_tx_fifo_outValue3_V_dummy_ack;
reg    ap_reg_ioackin_stat_reg_outValue1_V_dummy_ack;
reg    ap_reg_ioackin_stat_reg_outValue2_V_dummy_ack;
reg    ap_reg_ioackin_stat_reg_outValue3_V_dummy_ack;
reg    ap_reg_ioackin_stat_reg_outValue4_V_dummy_ack;
wire    ap_CS_fsm_state39;
reg   [38:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 39'd1;
#0 ap_reg_ioackin_iic_V_ARREADY = 1'b0;
#0 ap_reg_ioackin_iic_V_AWREADY = 1'b0;
#0 ap_reg_ioackin_iic_V_WREADY = 1'b0;
#0 ap_reg_ioackin_empty_pirq_outValue_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_length1_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_full_pirq_outValue_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_ctrl_reg_outValue_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_tx_fifo_outValue1_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_tx_fifo_outValue2_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_tx_fifo_outValue3_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_stat_reg_outValue1_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_stat_reg_outValue2_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_stat_reg_outValue3_V_dummy_ack = 1'b0;
#0 ap_reg_ioackin_stat_reg_outValue4_V_dummy_ack = 1'b0;
end

iiccomm3_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
iiccomm3_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .stat_reg_outValue1_V(iic_V_addr_2_read_reg_312),
    .stat_reg_outValue1_V_ap_vld(stat_reg_outValue1_V_ap_vld),
    .stat_reg_outValue2_V(iic_V_addr_2_read_reg_312),
    .stat_reg_outValue2_V_ap_vld(stat_reg_outValue2_V_ap_vld),
    .stat_reg_outValue3_V(iic_V_addr_2_read_reg_312),
    .stat_reg_outValue3_V_ap_vld(stat_reg_outValue3_V_ap_vld),
    .stat_reg_outValue4_V(iic_V_addr_2_read_reg_312),
    .stat_reg_outValue4_V_ap_vld(stat_reg_outValue4_V_ap_vld),
    .ctrl_reg_outValue_V(32'd1),
    .ctrl_reg_outValue_V_ap_vld(ctrl_reg_outValue_V_ap_vld),
    .empty_pirq_outValue_V(iic_V_addr_read_reg_295),
    .empty_pirq_outValue_V_ap_vld(empty_pirq_outValue_V_ap_vld),
    .full_pirq_outValue_V(32'd15),
    .full_pirq_outValue_V_ap_vld(full_pirq_outValue_V_ap_vld),
    .tx_fifo_outValue1_V(32'd492),
    .tx_fifo_outValue1_V_ap_vld(tx_fifo_outValue1_V_ap_vld),
    .tx_fifo_outValue2_V(32'd208),
    .tx_fifo_outValue2_V_ap_vld(tx_fifo_outValue2_V_ap_vld),
    .tx_fifo_outValue3_V(32'd493),
    .tx_fifo_outValue3_V_ap_vld(tx_fifo_outValue3_V_ap_vld),
    .rx_fifo_outValue_V(iic_V_addr_4_read_reg_332),
    .rx_fifo_outValue_V_ap_vld(rx_fifo_outValue_V_ap_vld),
    .length1_V(32'd32),
    .length1_V_ap_vld(length1_V_ap_vld)
);

iiccomm3_iic_V_m_axi #(
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_IIC_V_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_IIC_V_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_IIC_V_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_IIC_V_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_IIC_V_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_IIC_V_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_IIC_V_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_IIC_V_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_IIC_V_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_IIC_V_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_IIC_V_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_IIC_V_CACHE_VALUE ))
iiccomm3_iic_V_m_axi_U(
    .AWVALID(m_axi_iic_V_AWVALID),
    .AWREADY(m_axi_iic_V_AWREADY),
    .AWADDR(m_axi_iic_V_AWADDR),
    .AWID(m_axi_iic_V_AWID),
    .AWLEN(m_axi_iic_V_AWLEN),
    .AWSIZE(m_axi_iic_V_AWSIZE),
    .AWBURST(m_axi_iic_V_AWBURST),
    .AWLOCK(m_axi_iic_V_AWLOCK),
    .AWCACHE(m_axi_iic_V_AWCACHE),
    .AWPROT(m_axi_iic_V_AWPROT),
    .AWQOS(m_axi_iic_V_AWQOS),
    .AWREGION(m_axi_iic_V_AWREGION),
    .AWUSER(m_axi_iic_V_AWUSER),
    .WVALID(m_axi_iic_V_WVALID),
    .WREADY(m_axi_iic_V_WREADY),
    .WDATA(m_axi_iic_V_WDATA),
    .WSTRB(m_axi_iic_V_WSTRB),
    .WLAST(m_axi_iic_V_WLAST),
    .WID(m_axi_iic_V_WID),
    .WUSER(m_axi_iic_V_WUSER),
    .ARVALID(m_axi_iic_V_ARVALID),
    .ARREADY(m_axi_iic_V_ARREADY),
    .ARADDR(m_axi_iic_V_ARADDR),
    .ARID(m_axi_iic_V_ARID),
    .ARLEN(m_axi_iic_V_ARLEN),
    .ARSIZE(m_axi_iic_V_ARSIZE),
    .ARBURST(m_axi_iic_V_ARBURST),
    .ARLOCK(m_axi_iic_V_ARLOCK),
    .ARCACHE(m_axi_iic_V_ARCACHE),
    .ARPROT(m_axi_iic_V_ARPROT),
    .ARQOS(m_axi_iic_V_ARQOS),
    .ARREGION(m_axi_iic_V_ARREGION),
    .ARUSER(m_axi_iic_V_ARUSER),
    .RVALID(m_axi_iic_V_RVALID),
    .RREADY(m_axi_iic_V_RREADY),
    .RDATA(m_axi_iic_V_RDATA),
    .RLAST(m_axi_iic_V_RLAST),
    .RID(m_axi_iic_V_RID),
    .RUSER(m_axi_iic_V_RUSER),
    .RRESP(m_axi_iic_V_RRESP),
    .BVALID(m_axi_iic_V_BVALID),
    .BREADY(m_axi_iic_V_BREADY),
    .BRESP(m_axi_iic_V_BRESP),
    .BID(m_axi_iic_V_BID),
    .BUSER(m_axi_iic_V_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(iic_V_ARVALID),
    .I_ARREADY(iic_V_ARREADY),
    .I_ARADDR(iic_V_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(iic_V_RVALID),
    .I_RREADY(iic_V_RREADY),
    .I_RDATA(iic_V_RDATA),
    .I_RID(iic_V_RID),
    .I_RUSER(iic_V_RUSER),
    .I_RRESP(iic_V_RRESP),
    .I_RLAST(iic_V_RLAST),
    .I_AWVALID(iic_V_AWVALID),
    .I_AWREADY(iic_V_AWREADY),
    .I_AWADDR(iic_V_AWADDR),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(iic_V_WVALID),
    .I_WREADY(iic_V_WREADY),
    .I_WDATA(iic_V_WDATA),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(iic_V_BVALID),
    .I_BREADY(iic_V_BREADY),
    .I_BRESP(iic_V_BRESP),
    .I_BID(iic_V_BID),
    .I_BUSER(iic_V_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_ctrl_reg_outValue_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            if ((1'b0 == ap_block_state10_io)) begin
                ap_reg_ioackin_ctrl_reg_outValue_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_ctrl_reg_outValue_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_empty_pirq_outValue_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            if ((1'b0 == ap_block_state10_io)) begin
                ap_reg_ioackin_empty_pirq_outValue_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_empty_pirq_outValue_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_full_pirq_outValue_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            if ((1'b0 == ap_block_state10_io)) begin
                ap_reg_ioackin_full_pirq_outValue_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_full_pirq_outValue_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_iic_V_ARREADY <= 1'b0;
    end else begin
        if (((~((ap_start == 1'b0) | (ap_sig_ioackin_iic_V_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1)) | ((ap_sig_ioackin_iic_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state31)) | ((ap_sig_ioackin_iic_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17)))) begin
            ap_reg_ioackin_iic_V_ARREADY <= 1'b0;
        end else if ((((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (iic_V_ARREADY == 1'b1)) | ((iic_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state31)) | ((iic_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17)))) begin
            ap_reg_ioackin_iic_V_ARREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_iic_V_AWREADY <= 1'b0;
    end else begin
        if (((~((ap_sig_ioackin_iic_V_AWREADY == 1'b0) | (iic_V_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state24)) | ((1'b0 == ap_block_state10_io) & (1'b1 == ap_CS_fsm_state10)) | ((ap_sig_ioackin_iic_V_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
            ap_reg_ioackin_iic_V_AWREADY <= 1'b0;
        end else if ((((iic_V_RVALID == 1'b1) & (iic_V_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state24)) | ((iic_V_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10)) | ((iic_V_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
            ap_reg_ioackin_iic_V_AWREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_iic_V_WREADY <= 1'b0;
    end else begin
        if ((((ap_sig_ioackin_iic_V_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((ap_sig_ioackin_iic_V_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((1'b0 == ap_block_state10_io) & (1'b1 == ap_CS_fsm_state10)))) begin
            ap_reg_ioackin_iic_V_WREADY <= 1'b0;
        end else if ((((iic_V_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((iic_V_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((iic_V_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
            ap_reg_ioackin_iic_V_WREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_length1_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            if ((1'b0 == ap_block_state10_io)) begin
                ap_reg_ioackin_length1_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_length1_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_stat_reg_outValue1_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            if ((ap_sig_ioackin_iic_V_WREADY == 1'b1)) begin
                ap_reg_ioackin_stat_reg_outValue1_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_stat_reg_outValue1_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_stat_reg_outValue2_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            if ((ap_sig_ioackin_iic_V_WREADY == 1'b1)) begin
                ap_reg_ioackin_stat_reg_outValue2_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_stat_reg_outValue2_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_stat_reg_outValue3_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            if ((ap_sig_ioackin_iic_V_WREADY == 1'b1)) begin
                ap_reg_ioackin_stat_reg_outValue3_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_stat_reg_outValue3_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_stat_reg_outValue4_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            if ((ap_sig_ioackin_iic_V_WREADY == 1'b1)) begin
                ap_reg_ioackin_stat_reg_outValue4_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_stat_reg_outValue4_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_tx_fifo_outValue1_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            if ((1'b0 == ap_block_state10_io)) begin
                ap_reg_ioackin_tx_fifo_outValue1_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_tx_fifo_outValue1_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_tx_fifo_outValue2_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            if ((1'b0 == ap_block_state10_io)) begin
                ap_reg_ioackin_tx_fifo_outValue2_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_tx_fifo_outValue2_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_tx_fifo_outValue3_V_dummy_ack <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            if ((1'b0 == ap_block_state10_io)) begin
                ap_reg_ioackin_tx_fifo_outValue3_V_dummy_ack <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_reg_ioackin_tx_fifo_outValue3_V_dummy_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_ioackin_iic_V_AWREADY == 1'b0) | (iic_V_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state24))) begin
        iic_V_addr_2_read_reg_312 <= iic_V_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((iic_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state38))) begin
        iic_V_addr_4_read_reg_332 <= iic_V_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((iic_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        iic_V_addr_read_reg_295 <= iic_V_RDATA;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_iic_V_ARREADY == 1'b0)) begin
        ap_sig_ioackin_iic_V_ARREADY = iic_V_ARREADY;
    end else begin
        ap_sig_ioackin_iic_V_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_iic_V_AWREADY == 1'b0)) begin
        ap_sig_ioackin_iic_V_AWREADY = iic_V_AWREADY;
    end else begin
        ap_sig_ioackin_iic_V_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_iic_V_WREADY == 1'b0)) begin
        ap_sig_ioackin_iic_V_WREADY = iic_V_WREADY;
    end else begin
        ap_sig_ioackin_iic_V_WREADY = 1'b1;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_ctrl_reg_outValue_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ctrl_reg_outValue_V_ap_vld = 1'b1;
    end else begin
        ctrl_reg_outValue_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_empty_pirq_outValue_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        empty_pirq_outValue_V_ap_vld = 1'b1;
    end else begin
        empty_pirq_outValue_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_full_pirq_outValue_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        full_pirq_outValue_V_ap_vld = 1'b1;
    end else begin
        full_pirq_outValue_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_iic_V_ARREADY == 1'b0)) begin
        if ((1'b1 == ap_CS_fsm_state31)) begin
            iic_V_ARADDR = 64'd268436547;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            iic_V_ARADDR = 64'd268436545;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            iic_V_ARADDR = 64'd268436552;
        end else begin
            iic_V_ARADDR = 'bx;
        end
    end else begin
        iic_V_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b1) & (ap_reg_ioackin_iic_V_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_reg_ioackin_iic_V_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state31)) | ((ap_reg_ioackin_iic_V_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state17)))) begin
        iic_V_ARVALID = 1'b1;
    end else begin
        iic_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_iic_V_AWREADY == 1'b0)) begin
        if (((iic_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
            iic_V_AWADDR = 64'd268436546;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            iic_V_AWADDR = 64'd268436544;
        end else if ((1'b1 == ap_CS_fsm_state9)) begin
            iic_V_AWADDR = 64'd268436552;
        end else begin
            iic_V_AWADDR = 'bx;
        end
    end else begin
        iic_V_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((iic_V_RVALID == 1'b1) & (ap_reg_ioackin_iic_V_AWREADY == 1'b0) & (1'b1 == ap_CS_fsm_state24)) | ((ap_reg_ioackin_iic_V_AWREADY == 1'b0) & (1'b1 == ap_CS_fsm_state10)) | ((ap_reg_ioackin_iic_V_AWREADY == 1'b0) & (1'b1 == ap_CS_fsm_state9)))) begin
        iic_V_AWVALID = 1'b1;
    end else begin
        iic_V_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((iic_V_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state30)) | ((iic_V_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((iic_V_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15)))) begin
        iic_V_BREADY = 1'b1;
    end else begin
        iic_V_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((iic_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state38)) | (~((ap_sig_ioackin_iic_V_AWREADY == 1'b0) | (iic_V_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state24)) | ((iic_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        iic_V_RREADY = 1'b1;
    end else begin
        iic_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_iic_V_WREADY == 1'b0)) begin
        if ((1'b1 == ap_CS_fsm_state25)) begin
            iic_V_WDATA = 32'd513;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            iic_V_WDATA = 32'd1;
        end else if ((1'b1 == ap_CS_fsm_state10)) begin
            iic_V_WDATA = 32'd15;
        end else begin
            iic_V_WDATA = 'bx;
        end
    end else begin
        iic_V_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_reg_ioackin_iic_V_WREADY == 1'b0) & (1'b1 == ap_CS_fsm_state25)) | ((ap_reg_ioackin_iic_V_WREADY == 1'b0) & (1'b1 == ap_CS_fsm_state11)) | ((ap_reg_ioackin_iic_V_WREADY == 1'b0) & (1'b1 == ap_CS_fsm_state10)))) begin
        iic_V_WVALID = 1'b1;
    end else begin
        iic_V_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state17) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        iic_V_blk_n_AR = m_axi_iic_V_ARREADY;
    end else begin
        iic_V_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        iic_V_blk_n_AW = m_axi_iic_V_AWREADY;
    end else begin
        iic_V_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15))) begin
        iic_V_blk_n_B = m_axi_iic_V_BVALID;
    end else begin
        iic_V_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state8))) begin
        iic_V_blk_n_R = m_axi_iic_V_RVALID;
    end else begin
        iic_V_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        iic_V_blk_n_W = m_axi_iic_V_WREADY;
    end else begin
        iic_V_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_length1_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        length1_V_ap_vld = 1'b1;
    end else begin
        length1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        rx_fifo_outValue_V_ap_vld = 1'b1;
    end else begin
        rx_fifo_outValue_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_stat_reg_outValue1_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state25))) begin
        stat_reg_outValue1_V_ap_vld = 1'b1;
    end else begin
        stat_reg_outValue1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_stat_reg_outValue2_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state25))) begin
        stat_reg_outValue2_V_ap_vld = 1'b1;
    end else begin
        stat_reg_outValue2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_stat_reg_outValue3_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state25))) begin
        stat_reg_outValue3_V_ap_vld = 1'b1;
    end else begin
        stat_reg_outValue3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_stat_reg_outValue4_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state25))) begin
        stat_reg_outValue4_V_ap_vld = 1'b1;
    end else begin
        stat_reg_outValue4_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_tx_fifo_outValue1_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        tx_fifo_outValue1_V_ap_vld = 1'b1;
    end else begin
        tx_fifo_outValue1_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_tx_fifo_outValue2_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        tx_fifo_outValue2_V_ap_vld = 1'b1;
    end else begin
        tx_fifo_outValue2_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_tx_fifo_outValue3_V_dummy_ack == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        tx_fifo_outValue3_V_ap_vld = 1'b1;
    end else begin
        tx_fifo_outValue3_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_sig_ioackin_iic_V_ARREADY == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((iic_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((ap_sig_ioackin_iic_V_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_io) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((ap_sig_ioackin_iic_V_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((iic_V_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((iic_V_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((ap_sig_ioackin_iic_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if ((~((ap_sig_ioackin_iic_V_AWREADY == 1'b0) | (iic_V_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((ap_sig_ioackin_iic_V_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((iic_V_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            if (((ap_sig_ioackin_iic_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            if (((iic_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_io = ((ap_sig_ioackin_iic_V_AWREADY == 1'b0) | (ap_sig_ioackin_iic_V_WREADY == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

endmodule //iiccomm3
