// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x000 : Control signals
//         bit 0  - ap_start (Read/Write/COH)
//         bit 1  - ap_done (Read/COR)
//         bit 2  - ap_idle (Read)
//         bit 3  - ap_ready (Read)
//         bit 7  - auto_restart (Read/Write)
//         others - reserved
// 0x004 : Global Interrupt Enable Register
//         bit 0  - Global Interrupt Enable (Read/Write)
//         others - reserved
// 0x008 : IP Interrupt Enable Register (Read/Write)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x00c : IP Interrupt Status Register (Read/TOW)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x010 : Data signal of stat_reg_outValue1_i
//         bit 31~0 - stat_reg_outValue1_i[31:0] (Read/Write)
// 0x014 : reserved
// 0x018 : Data signal of stat_reg_outValue1_o
//         bit 31~0 - stat_reg_outValue1_o[31:0] (Read)
// 0x01c : Control signal of stat_reg_outValue1_o
//         bit 0  - stat_reg_outValue1_o_ap_vld (Read/COR)
//         others - reserved
// 0x020 : Data signal of empty_pirq_outValue_i
//         bit 31~0 - empty_pirq_outValue_i[31:0] (Read/Write)
// 0x024 : reserved
// 0x028 : Data signal of empty_pirq_outValue_o
//         bit 31~0 - empty_pirq_outValue_o[31:0] (Read)
// 0x02c : Control signal of empty_pirq_outValue_o
//         bit 0  - empty_pirq_outValue_o_ap_vld (Read/COR)
//         others - reserved
// 0x030 : Data signal of full_pirq_outValue_i
//         bit 31~0 - full_pirq_outValue_i[31:0] (Read/Write)
// 0x034 : reserved
// 0x038 : Data signal of full_pirq_outValue_o
//         bit 31~0 - full_pirq_outValue_o[31:0] (Read)
// 0x03c : Control signal of full_pirq_outValue_o
//         bit 0  - full_pirq_outValue_o_ap_vld (Read/COR)
//         others - reserved
// 0x040 : Data signal of ctrl_reg_outValue1_i
//         bit 31~0 - ctrl_reg_outValue1_i[31:0] (Read/Write)
// 0x044 : reserved
// 0x048 : Data signal of ctrl_reg_outValue1_o
//         bit 31~0 - ctrl_reg_outValue1_o[31:0] (Read)
// 0x04c : Control signal of ctrl_reg_outValue1_o
//         bit 0  - ctrl_reg_outValue1_o_ap_vld (Read/COR)
//         others - reserved
// 0x050 : Data signal of clearedInterrStatus1_i
//         bit 31~0 - clearedInterrStatus1_i[31:0] (Read/Write)
// 0x054 : reserved
// 0x058 : Data signal of clearedInterrStatus1_o
//         bit 31~0 - clearedInterrStatus1_o[31:0] (Read)
// 0x05c : Control signal of clearedInterrStatus1_o
//         bit 0  - clearedInterrStatus1_o_ap_vld (Read/COR)
//         others - reserved
// 0x060 : Data signal of rxFifoDepth1_i
//         bit 31~0 - rxFifoDepth1_i[31:0] (Read/Write)
// 0x064 : reserved
// 0x068 : Data signal of rxFifoDepth1_o
//         bit 31~0 - rxFifoDepth1_o[31:0] (Read)
// 0x06c : Control signal of rxFifoDepth1_o
//         bit 0  - rxFifoDepth1_o_ap_vld (Read/COR)
//         others - reserved
// 0x070 : Data signal of resetAxiEnabled
//         bit 31~0 - resetAxiEnabled[31:0] (Read)
// 0x074 : Control signal of resetAxiEnabled
//         bit 0  - resetAxiEnabled_ap_vld (Read/COR)
//         others - reserved
// 0x078 : Data signal of ctrl2RegState_enabled
//         bit 31~0 - ctrl2RegState_enabled[31:0] (Read)
// 0x07c : Control signal of ctrl2RegState_enabled
//         bit 0  - ctrl2RegState_enabled_ap_vld (Read/COR)
//         others - reserved
// 0x080 : Data signal of byteCountZero
//         bit 31~0 - byteCountZero[31:0] (Read/Write)
// 0x084 : reserved
// 0x088 : Data signal of clearedInterruptStatus2
//         bit 31~0 - clearedInterruptStatus2[31:0] (Read/Write)
// 0x08c : reserved
// 0x090 : Data signal of interrStatus2_i
//         bit 31~0 - interrStatus2_i[31:0] (Read/Write)
// 0x094 : reserved
// 0x098 : Data signal of interrStatus2_o
//         bit 31~0 - interrStatus2_o[31:0] (Read)
// 0x09c : Control signal of interrStatus2_o
//         bit 0  - interrStatus2_o_ap_vld (Read/COR)
//         others - reserved
// 0x0a0 : Data signal of disableTxBitDirection
//         bit 31~0 - disableTxBitDirection[31:0] (Read)
// 0x0a4 : Control signal of disableTxBitDirection
//         bit 0  - disableTxBitDirection_ap_vld (Read/COR)
//         others - reserved
// 0x0a8 : Data signal of pressByteCountEnabled
//         bit 31~0 - pressByteCountEnabled[31:0] (Read)
// 0x0ac : Control signal of pressByteCountEnabled
//         bit 0  - pressByteCountEnabled_ap_vld (Read/COR)
//         others - reserved
// 0x0b0 : Data signal of byteTracker
//         bit 31~0 - byteTracker[31:0] (Read)
// 0x0b4 : Control signal of byteTracker
//         bit 0  - byteTracker_ap_vld (Read/COR)
//         others - reserved
// 0x0b8 : Data signal of interrStatus3StateEnabled
//         bit 31~0 - interrStatus3StateEnabled[31:0] (Read)
// 0x0bc : Control signal of interrStatus3StateEnabled
//         bit 0  - interrStatus3StateEnabled_ap_vld (Read/COR)
//         others - reserved
// 0x0c0 : Data signal of checkInterrReg
//         bit 31~0 - checkInterrReg[31:0] (Read)
// 0x0c4 : Control signal of checkInterrReg
//         bit 0  - checkInterrReg_ap_vld (Read/COR)
//         others - reserved
// 0x0c8 : Data signal of ctrl_reg_val3_i
//         bit 31~0 - ctrl_reg_val3_i[31:0] (Read/Write)
// 0x0cc : reserved
// 0x0d0 : Data signal of ctrl_reg_val3_o
//         bit 31~0 - ctrl_reg_val3_o[31:0] (Read)
// 0x0d4 : Control signal of ctrl_reg_val3_o
//         bit 0  - ctrl_reg_val3_o_ap_vld (Read/COR)
//         others - reserved
// 0x0d8 : Data signal of lastByteRead_i
//         bit 31~0 - lastByteRead_i[31:0] (Read/Write)
// 0x0dc : reserved
// 0x0e0 : Data signal of lastByteRead_o
//         bit 31~0 - lastByteRead_o[31:0] (Read)
// 0x0e4 : Control signal of lastByteRead_o
//         bit 0  - lastByteRead_o_ap_vld (Read/COR)
//         others - reserved
// 0x0e8 : Data signal of rx_fifo_Outvalue_i
//         bit 31~0 - rx_fifo_Outvalue_i[31:0] (Read/Write)
// 0x0ec : reserved
// 0x0f0 : Data signal of rx_fifo_Outvalue_o
//         bit 31~0 - rx_fifo_Outvalue_o[31:0] (Read)
// 0x0f4 : Control signal of rx_fifo_Outvalue_o
//         bit 0  - rx_fifo_Outvalue_o_ap_vld (Read/COR)
//         others - reserved
// 0x0f8 : Data signal of clearLatchedInterr_i
//         bit 31~0 - clearLatchedInterr_i[31:0] (Read/Write)
// 0x0fc : reserved
// 0x100 : Data signal of clearLatchedInterr_o
//         bit 31~0 - clearLatchedInterr_o[31:0] (Read)
// 0x104 : Control signal of clearLatchedInterr_o
//         bit 0  - clearLatchedInterr_o_ap_vld (Read/COR)
//         others - reserved
// 0x108 : Data signal of releaseBus
//         bit 31~0 - releaseBus[31:0] (Read)
// 0x10c : Control signal of releaseBus
//         bit 0  - releaseBus_ap_vld (Read/COR)
//         others - reserved
// 0x110 : Data signal of receivedSuccess
//         bit 31~0 - receivedSuccess[31:0] (Read)
// 0x114 : Control signal of receivedSuccess
//         bit 0  - receivedSuccess_ap_vld (Read/COR)
//         others - reserved
// 0x118 : Data signal of pressure_msb_i
//         bit 31~0 - pressure_msb_i[31:0] (Read/Write)
// 0x11c : reserved
// 0x120 : Data signal of pressure_msb_o
//         bit 31~0 - pressure_msb_o[31:0] (Read)
// 0x124 : Control signal of pressure_msb_o
//         bit 0  - pressure_msb_o_ap_vld (Read/COR)
//         others - reserved
// 0x128 : Data signal of pressure_lsb_i
//         bit 31~0 - pressure_lsb_i[31:0] (Read/Write)
// 0x12c : reserved
// 0x130 : Data signal of pressure_lsb_o
//         bit 31~0 - pressure_lsb_o[31:0] (Read)
// 0x134 : Control signal of pressure_lsb_o
//         bit 0  - pressure_lsb_o_ap_vld (Read/COR)
//         others - reserved
// 0x138 : Data signal of pressure_xlsb_i
//         bit 31~0 - pressure_xlsb_i[31:0] (Read/Write)
// 0x13c : reserved
// 0x140 : Data signal of pressure_xlsb_o
//         bit 31~0 - pressure_xlsb_o[31:0] (Read)
// 0x144 : Control signal of pressure_xlsb_o
//         bit 0  - pressure_xlsb_o_ap_vld (Read/COR)
//         others - reserved
// 0x148 : Data signal of stat_reg_val6_state
//         bit 31~0 - stat_reg_val6_state[31:0] (Read)
// 0x14c : Control signal of stat_reg_val6_state
//         bit 0  - stat_reg_val6_state_ap_vld (Read/COR)
//         others - reserved
// 0x150 : Data signal of ctrl_reg_val2
//         bit 31~0 - ctrl_reg_val2[31:0] (Read)
// 0x154 : Control signal of ctrl_reg_val2
//         bit 0  - ctrl_reg_val2_ap_vld (Read/COR)
//         others - reserved
// 0x158 : Data signal of ctrl2RegState
//         bit 31~0 - ctrl2RegState[31:0] (Read)
// 0x15c : Control signal of ctrl2RegState
//         bit 0  - ctrl2RegState_ap_vld (Read/COR)
//         others - reserved
// 0x160 : Data signal of ctrl_reg_check
//         bit 31~0 - ctrl_reg_check[31:0] (Read)
// 0x164 : Control signal of ctrl_reg_check
//         bit 0  - ctrl_reg_check_ap_vld (Read/COR)
//         others - reserved
// 0x168 : Data signal of zeroBytes
//         bit 31~0 - zeroBytes[31:0] (Read/Write)
// 0x16c : reserved
// 0x170 : Data signal of interrStatus3State
//         bit 31~0 - interrStatus3State[31:0] (Read)
// 0x174 : Control signal of interrStatus3State
//         bit 0  - interrStatus3State_ap_vld (Read/COR)
//         others - reserved
// 0x178 : Data signal of interrStatus5State
//         bit 31~0 - interrStatus5State[31:0] (Read)
// 0x17c : Control signal of interrStatus5State
//         bit 0  - interrStatus5State_ap_vld (Read/COR)
//         others - reserved
// 0x180 : Data signal of tx_fifo_1
//         bit 31~0 - tx_fifo_1[31:0] (Read)
// 0x184 : Control signal of tx_fifo_1
//         bit 0  - tx_fifo_1_ap_vld (Read/COR)
//         others - reserved
// 0x188 : Data signal of tx_fifo_2
//         bit 31~0 - tx_fifo_2[31:0] (Read)
// 0x18c : Control signal of tx_fifo_2
//         bit 0  - tx_fifo_2_ap_vld (Read/COR)
//         others - reserved
// 0x190 : Data signal of interrStatus
//         bit 31~0 - interrStatus[31:0] (Read)
// 0x194 : Control signal of interrStatus
//         bit 0  - interrStatus_ap_vld (Read/COR)
//         others - reserved
// 0x198 : Data signal of stat_reg_val
//         bit 31~0 - stat_reg_val[31:0] (Read)
// 0x19c : Control signal of stat_reg_val
//         bit 0  - stat_reg_val_ap_vld (Read/COR)
//         others - reserved
// 0x1a0 : Data signal of statRegState
//         bit 31~0 - statRegState[31:0] (Read)
// 0x1a4 : Control signal of statRegState
//         bit 0  - statRegState_ap_vld (Read/COR)
//         others - reserved
// 0x1a8 : Data signal of clearInterrStatus
//         bit 31~0 - clearInterrStatus[31:0] (Read)
// 0x1ac : Control signal of clearInterrStatus
//         bit 0  - clearInterrStatus_ap_vld (Read/COR)
//         others - reserved
// 0x1b0 : Data signal of clearInterrStatusCheck
//         bit 31~0 - clearInterrStatusCheck[31:0] (Read)
// 0x1b4 : Control signal of clearInterrStatusCheck
//         bit 0  - clearInterrStatusCheck_ap_vld (Read/COR)
//         others - reserved
// 0x1b8 : Data signal of error1
//         bit 31~0 - error1[31:0] (Read/Write)
// 0x1bc : reserved
// 0x1c0 : Data signal of tx_fifo_3
//         bit 31~0 - tx_fifo_3[31:0] (Read)
// 0x1c4 : Control signal of tx_fifo_3
//         bit 0  - tx_fifo_3_ap_vld (Read/COR)
//         others - reserved
// 0x1c8 : Data signal of interrStatus3
//         bit 31~0 - interrStatus3[31:0] (Read)
// 0x1cc : Control signal of interrStatus3
//         bit 0  - interrStatus3_ap_vld (Read/COR)
//         others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBMESENSOR2_AXILITES_ADDR_AP_CTRL                        0x000
#define XBMESENSOR2_AXILITES_ADDR_GIE                            0x004
#define XBMESENSOR2_AXILITES_ADDR_IER                            0x008
#define XBMESENSOR2_AXILITES_ADDR_ISR                            0x00c
#define XBMESENSOR2_AXILITES_ADDR_STAT_REG_OUTVALUE1_I_DATA      0x010
#define XBMESENSOR2_AXILITES_BITS_STAT_REG_OUTVALUE1_I_DATA      32
#define XBMESENSOR2_AXILITES_ADDR_STAT_REG_OUTVALUE1_O_DATA      0x018
#define XBMESENSOR2_AXILITES_BITS_STAT_REG_OUTVALUE1_O_DATA      32
#define XBMESENSOR2_AXILITES_ADDR_STAT_REG_OUTVALUE1_O_CTRL      0x01c
#define XBMESENSOR2_AXILITES_ADDR_EMPTY_PIRQ_OUTVALUE_I_DATA     0x020
#define XBMESENSOR2_AXILITES_BITS_EMPTY_PIRQ_OUTVALUE_I_DATA     32
#define XBMESENSOR2_AXILITES_ADDR_EMPTY_PIRQ_OUTVALUE_O_DATA     0x028
#define XBMESENSOR2_AXILITES_BITS_EMPTY_PIRQ_OUTVALUE_O_DATA     32
#define XBMESENSOR2_AXILITES_ADDR_EMPTY_PIRQ_OUTVALUE_O_CTRL     0x02c
#define XBMESENSOR2_AXILITES_ADDR_FULL_PIRQ_OUTVALUE_I_DATA      0x030
#define XBMESENSOR2_AXILITES_BITS_FULL_PIRQ_OUTVALUE_I_DATA      32
#define XBMESENSOR2_AXILITES_ADDR_FULL_PIRQ_OUTVALUE_O_DATA      0x038
#define XBMESENSOR2_AXILITES_BITS_FULL_PIRQ_OUTVALUE_O_DATA      32
#define XBMESENSOR2_AXILITES_ADDR_FULL_PIRQ_OUTVALUE_O_CTRL      0x03c
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_OUTVALUE1_I_DATA      0x040
#define XBMESENSOR2_AXILITES_BITS_CTRL_REG_OUTVALUE1_I_DATA      32
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_OUTVALUE1_O_DATA      0x048
#define XBMESENSOR2_AXILITES_BITS_CTRL_REG_OUTVALUE1_O_DATA      32
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_OUTVALUE1_O_CTRL      0x04c
#define XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRSTATUS1_I_DATA    0x050
#define XBMESENSOR2_AXILITES_BITS_CLEAREDINTERRSTATUS1_I_DATA    32
#define XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRSTATUS1_O_DATA    0x058
#define XBMESENSOR2_AXILITES_BITS_CLEAREDINTERRSTATUS1_O_DATA    32
#define XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRSTATUS1_O_CTRL    0x05c
#define XBMESENSOR2_AXILITES_ADDR_RXFIFODEPTH1_I_DATA            0x060
#define XBMESENSOR2_AXILITES_BITS_RXFIFODEPTH1_I_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_RXFIFODEPTH1_O_DATA            0x068
#define XBMESENSOR2_AXILITES_BITS_RXFIFODEPTH1_O_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_RXFIFODEPTH1_O_CTRL            0x06c
#define XBMESENSOR2_AXILITES_ADDR_RESETAXIENABLED_DATA           0x070
#define XBMESENSOR2_AXILITES_BITS_RESETAXIENABLED_DATA           32
#define XBMESENSOR2_AXILITES_ADDR_RESETAXIENABLED_CTRL           0x074
#define XBMESENSOR2_AXILITES_ADDR_CTRL2REGSTATE_ENABLED_DATA     0x078
#define XBMESENSOR2_AXILITES_BITS_CTRL2REGSTATE_ENABLED_DATA     32
#define XBMESENSOR2_AXILITES_ADDR_CTRL2REGSTATE_ENABLED_CTRL     0x07c
#define XBMESENSOR2_AXILITES_ADDR_BYTECOUNTZERO_DATA             0x080
#define XBMESENSOR2_AXILITES_BITS_BYTECOUNTZERO_DATA             32
#define XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRUPTSTATUS2_DATA   0x088
#define XBMESENSOR2_AXILITES_BITS_CLEAREDINTERRUPTSTATUS2_DATA   32
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS2_I_DATA           0x090
#define XBMESENSOR2_AXILITES_BITS_INTERRSTATUS2_I_DATA           32
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS2_O_DATA           0x098
#define XBMESENSOR2_AXILITES_BITS_INTERRSTATUS2_O_DATA           32
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS2_O_CTRL           0x09c
#define XBMESENSOR2_AXILITES_ADDR_DISABLETXBITDIRECTION_DATA     0x0a0
#define XBMESENSOR2_AXILITES_BITS_DISABLETXBITDIRECTION_DATA     32
#define XBMESENSOR2_AXILITES_ADDR_DISABLETXBITDIRECTION_CTRL     0x0a4
#define XBMESENSOR2_AXILITES_ADDR_PRESSBYTECOUNTENABLED_DATA     0x0a8
#define XBMESENSOR2_AXILITES_BITS_PRESSBYTECOUNTENABLED_DATA     32
#define XBMESENSOR2_AXILITES_ADDR_PRESSBYTECOUNTENABLED_CTRL     0x0ac
#define XBMESENSOR2_AXILITES_ADDR_BYTETRACKER_DATA               0x0b0
#define XBMESENSOR2_AXILITES_BITS_BYTETRACKER_DATA               32
#define XBMESENSOR2_AXILITES_ADDR_BYTETRACKER_CTRL               0x0b4
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3STATEENABLED_DATA 0x0b8
#define XBMESENSOR2_AXILITES_BITS_INTERRSTATUS3STATEENABLED_DATA 32
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3STATEENABLED_CTRL 0x0bc
#define XBMESENSOR2_AXILITES_ADDR_CHECKINTERRREG_DATA            0x0c0
#define XBMESENSOR2_AXILITES_BITS_CHECKINTERRREG_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_CHECKINTERRREG_CTRL            0x0c4
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL3_I_DATA           0x0c8
#define XBMESENSOR2_AXILITES_BITS_CTRL_REG_VAL3_I_DATA           32
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL3_O_DATA           0x0d0
#define XBMESENSOR2_AXILITES_BITS_CTRL_REG_VAL3_O_DATA           32
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL3_O_CTRL           0x0d4
#define XBMESENSOR2_AXILITES_ADDR_LASTBYTEREAD_I_DATA            0x0d8
#define XBMESENSOR2_AXILITES_BITS_LASTBYTEREAD_I_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_LASTBYTEREAD_O_DATA            0x0e0
#define XBMESENSOR2_AXILITES_BITS_LASTBYTEREAD_O_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_LASTBYTEREAD_O_CTRL            0x0e4
#define XBMESENSOR2_AXILITES_ADDR_RX_FIFO_OUTVALUE_I_DATA        0x0e8
#define XBMESENSOR2_AXILITES_BITS_RX_FIFO_OUTVALUE_I_DATA        32
#define XBMESENSOR2_AXILITES_ADDR_RX_FIFO_OUTVALUE_O_DATA        0x0f0
#define XBMESENSOR2_AXILITES_BITS_RX_FIFO_OUTVALUE_O_DATA        32
#define XBMESENSOR2_AXILITES_ADDR_RX_FIFO_OUTVALUE_O_CTRL        0x0f4
#define XBMESENSOR2_AXILITES_ADDR_CLEARLATCHEDINTERR_I_DATA      0x0f8
#define XBMESENSOR2_AXILITES_BITS_CLEARLATCHEDINTERR_I_DATA      32
#define XBMESENSOR2_AXILITES_ADDR_CLEARLATCHEDINTERR_O_DATA      0x100
#define XBMESENSOR2_AXILITES_BITS_CLEARLATCHEDINTERR_O_DATA      32
#define XBMESENSOR2_AXILITES_ADDR_CLEARLATCHEDINTERR_O_CTRL      0x104
#define XBMESENSOR2_AXILITES_ADDR_RELEASEBUS_DATA                0x108
#define XBMESENSOR2_AXILITES_BITS_RELEASEBUS_DATA                32
#define XBMESENSOR2_AXILITES_ADDR_RELEASEBUS_CTRL                0x10c
#define XBMESENSOR2_AXILITES_ADDR_RECEIVEDSUCCESS_DATA           0x110
#define XBMESENSOR2_AXILITES_BITS_RECEIVEDSUCCESS_DATA           32
#define XBMESENSOR2_AXILITES_ADDR_RECEIVEDSUCCESS_CTRL           0x114
#define XBMESENSOR2_AXILITES_ADDR_PRESSURE_MSB_I_DATA            0x118
#define XBMESENSOR2_AXILITES_BITS_PRESSURE_MSB_I_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_PRESSURE_MSB_O_DATA            0x120
#define XBMESENSOR2_AXILITES_BITS_PRESSURE_MSB_O_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_PRESSURE_MSB_O_CTRL            0x124
#define XBMESENSOR2_AXILITES_ADDR_PRESSURE_LSB_I_DATA            0x128
#define XBMESENSOR2_AXILITES_BITS_PRESSURE_LSB_I_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_PRESSURE_LSB_O_DATA            0x130
#define XBMESENSOR2_AXILITES_BITS_PRESSURE_LSB_O_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_PRESSURE_LSB_O_CTRL            0x134
#define XBMESENSOR2_AXILITES_ADDR_PRESSURE_XLSB_I_DATA           0x138
#define XBMESENSOR2_AXILITES_BITS_PRESSURE_XLSB_I_DATA           32
#define XBMESENSOR2_AXILITES_ADDR_PRESSURE_XLSB_O_DATA           0x140
#define XBMESENSOR2_AXILITES_BITS_PRESSURE_XLSB_O_DATA           32
#define XBMESENSOR2_AXILITES_ADDR_PRESSURE_XLSB_O_CTRL           0x144
#define XBMESENSOR2_AXILITES_ADDR_STAT_REG_VAL6_STATE_DATA       0x148
#define XBMESENSOR2_AXILITES_BITS_STAT_REG_VAL6_STATE_DATA       32
#define XBMESENSOR2_AXILITES_ADDR_STAT_REG_VAL6_STATE_CTRL       0x14c
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL2_DATA             0x150
#define XBMESENSOR2_AXILITES_BITS_CTRL_REG_VAL2_DATA             32
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL2_CTRL             0x154
#define XBMESENSOR2_AXILITES_ADDR_CTRL2REGSTATE_DATA             0x158
#define XBMESENSOR2_AXILITES_BITS_CTRL2REGSTATE_DATA             32
#define XBMESENSOR2_AXILITES_ADDR_CTRL2REGSTATE_CTRL             0x15c
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_CHECK_DATA            0x160
#define XBMESENSOR2_AXILITES_BITS_CTRL_REG_CHECK_DATA            32
#define XBMESENSOR2_AXILITES_ADDR_CTRL_REG_CHECK_CTRL            0x164
#define XBMESENSOR2_AXILITES_ADDR_ZEROBYTES_DATA                 0x168
#define XBMESENSOR2_AXILITES_BITS_ZEROBYTES_DATA                 32
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3STATE_DATA        0x170
#define XBMESENSOR2_AXILITES_BITS_INTERRSTATUS3STATE_DATA        32
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3STATE_CTRL        0x174
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS5STATE_DATA        0x178
#define XBMESENSOR2_AXILITES_BITS_INTERRSTATUS5STATE_DATA        32
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS5STATE_CTRL        0x17c
#define XBMESENSOR2_AXILITES_ADDR_TX_FIFO_1_DATA                 0x180
#define XBMESENSOR2_AXILITES_BITS_TX_FIFO_1_DATA                 32
#define XBMESENSOR2_AXILITES_ADDR_TX_FIFO_1_CTRL                 0x184
#define XBMESENSOR2_AXILITES_ADDR_TX_FIFO_2_DATA                 0x188
#define XBMESENSOR2_AXILITES_BITS_TX_FIFO_2_DATA                 32
#define XBMESENSOR2_AXILITES_ADDR_TX_FIFO_2_CTRL                 0x18c
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS_DATA              0x190
#define XBMESENSOR2_AXILITES_BITS_INTERRSTATUS_DATA              32
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS_CTRL              0x194
#define XBMESENSOR2_AXILITES_ADDR_STAT_REG_VAL_DATA              0x198
#define XBMESENSOR2_AXILITES_BITS_STAT_REG_VAL_DATA              32
#define XBMESENSOR2_AXILITES_ADDR_STAT_REG_VAL_CTRL              0x19c
#define XBMESENSOR2_AXILITES_ADDR_STATREGSTATE_DATA              0x1a0
#define XBMESENSOR2_AXILITES_BITS_STATREGSTATE_DATA              32
#define XBMESENSOR2_AXILITES_ADDR_STATREGSTATE_CTRL              0x1a4
#define XBMESENSOR2_AXILITES_ADDR_CLEARINTERRSTATUS_DATA         0x1a8
#define XBMESENSOR2_AXILITES_BITS_CLEARINTERRSTATUS_DATA         32
#define XBMESENSOR2_AXILITES_ADDR_CLEARINTERRSTATUS_CTRL         0x1ac
#define XBMESENSOR2_AXILITES_ADDR_CLEARINTERRSTATUSCHECK_DATA    0x1b0
#define XBMESENSOR2_AXILITES_BITS_CLEARINTERRSTATUSCHECK_DATA    32
#define XBMESENSOR2_AXILITES_ADDR_CLEARINTERRSTATUSCHECK_CTRL    0x1b4
#define XBMESENSOR2_AXILITES_ADDR_ERROR1_DATA                    0x1b8
#define XBMESENSOR2_AXILITES_BITS_ERROR1_DATA                    32
#define XBMESENSOR2_AXILITES_ADDR_TX_FIFO_3_DATA                 0x1c0
#define XBMESENSOR2_AXILITES_BITS_TX_FIFO_3_DATA                 32
#define XBMESENSOR2_AXILITES_ADDR_TX_FIFO_3_CTRL                 0x1c4
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3_DATA             0x1c8
#define XBMESENSOR2_AXILITES_BITS_INTERRSTATUS3_DATA             32
#define XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3_CTRL             0x1cc

