// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xbmesensor2.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XBmesensor2_CfgInitialize(XBmesensor2 *InstancePtr, XBmesensor2_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XBmesensor2_Start(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_AP_CTRL) & 0x80;
    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XBmesensor2_IsDone(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XBmesensor2_IsIdle(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XBmesensor2_IsReady(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XBmesensor2_EnableAutoRestart(XBmesensor2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XBmesensor2_DisableAutoRestart(XBmesensor2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_AP_CTRL, 0);
}

void XBmesensor2_Set_stat_reg_outValue1_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STAT_REG_OUTVALUE1_I_DATA, Data);
}

u32 XBmesensor2_Get_stat_reg_outValue1_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STAT_REG_OUTVALUE1_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_stat_reg_outValue1_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STAT_REG_OUTVALUE1_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_stat_reg_outValue1_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STAT_REG_OUTVALUE1_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_empty_pirq_outValue_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_EMPTY_PIRQ_OUTVALUE_I_DATA, Data);
}

u32 XBmesensor2_Get_empty_pirq_outValue_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_EMPTY_PIRQ_OUTVALUE_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_empty_pirq_outValue_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_EMPTY_PIRQ_OUTVALUE_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_empty_pirq_outValue_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_EMPTY_PIRQ_OUTVALUE_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_full_pirq_outValue_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_FULL_PIRQ_OUTVALUE_I_DATA, Data);
}

u32 XBmesensor2_Get_full_pirq_outValue_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_FULL_PIRQ_OUTVALUE_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_full_pirq_outValue_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_FULL_PIRQ_OUTVALUE_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_full_pirq_outValue_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_FULL_PIRQ_OUTVALUE_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_ctrl_reg_outValue1_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_OUTVALUE1_I_DATA, Data);
}

u32 XBmesensor2_Get_ctrl_reg_outValue1_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_OUTVALUE1_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_ctrl_reg_outValue1_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_OUTVALUE1_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_ctrl_reg_outValue1_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_OUTVALUE1_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_clearedInterrStatus1_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRSTATUS1_I_DATA, Data);
}

u32 XBmesensor2_Get_clearedInterrStatus1_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRSTATUS1_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_clearedInterrStatus1_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRSTATUS1_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_clearedInterrStatus1_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRSTATUS1_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_rxFifoDepth1_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RXFIFODEPTH1_I_DATA, Data);
}

u32 XBmesensor2_Get_rxFifoDepth1_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RXFIFODEPTH1_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_rxFifoDepth1_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RXFIFODEPTH1_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_rxFifoDepth1_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RXFIFODEPTH1_O_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_resetAxiEnabled(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RESETAXIENABLED_DATA);
    return Data;
}

u32 XBmesensor2_Get_resetAxiEnabled_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RESETAXIENABLED_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_ctrl2RegState_enabled(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL2REGSTATE_ENABLED_DATA);
    return Data;
}

u32 XBmesensor2_Get_ctrl2RegState_enabled_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL2REGSTATE_ENABLED_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_byteCountZero(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_BYTECOUNTZERO_DATA, Data);
}

u32 XBmesensor2_Get_byteCountZero(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_BYTECOUNTZERO_DATA);
    return Data;
}

void XBmesensor2_Set_clearedInterruptStatus2(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRUPTSTATUS2_DATA, Data);
}

u32 XBmesensor2_Get_clearedInterruptStatus2(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEAREDINTERRUPTSTATUS2_DATA);
    return Data;
}

void XBmesensor2_Set_interrStatus2_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS2_I_DATA, Data);
}

u32 XBmesensor2_Get_interrStatus2_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS2_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_interrStatus2_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS2_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_interrStatus2_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS2_O_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_disableTxBitDirection(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_DISABLETXBITDIRECTION_DATA);
    return Data;
}

u32 XBmesensor2_Get_disableTxBitDirection_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_DISABLETXBITDIRECTION_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_pressByteCountEnabled(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSBYTECOUNTENABLED_DATA);
    return Data;
}

u32 XBmesensor2_Get_pressByteCountEnabled_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSBYTECOUNTENABLED_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_byteTracker(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_BYTETRACKER_DATA);
    return Data;
}

u32 XBmesensor2_Get_byteTracker_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_BYTETRACKER_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_interrStatus3StateEnabled(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3STATEENABLED_DATA);
    return Data;
}

u32 XBmesensor2_Get_interrStatus3StateEnabled_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3STATEENABLED_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_checkInterrReg(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CHECKINTERRREG_DATA);
    return Data;
}

u32 XBmesensor2_Get_checkInterrReg_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CHECKINTERRREG_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_ctrl_reg_val3_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL3_I_DATA, Data);
}

u32 XBmesensor2_Get_ctrl_reg_val3_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL3_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_ctrl_reg_val3_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL3_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_ctrl_reg_val3_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL3_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_lastByteRead_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_LASTBYTEREAD_I_DATA, Data);
}

u32 XBmesensor2_Get_lastByteRead_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_LASTBYTEREAD_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_lastByteRead_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_LASTBYTEREAD_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_lastByteRead_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_LASTBYTEREAD_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_rx_fifo_Outvalue_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RX_FIFO_OUTVALUE_I_DATA, Data);
}

u32 XBmesensor2_Get_rx_fifo_Outvalue_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RX_FIFO_OUTVALUE_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_rx_fifo_Outvalue_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RX_FIFO_OUTVALUE_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_rx_fifo_Outvalue_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RX_FIFO_OUTVALUE_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_clearLatchedInterr_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEARLATCHEDINTERR_I_DATA, Data);
}

u32 XBmesensor2_Get_clearLatchedInterr_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEARLATCHEDINTERR_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_clearLatchedInterr_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEARLATCHEDINTERR_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_clearLatchedInterr_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEARLATCHEDINTERR_O_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_releaseBus(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RELEASEBUS_DATA);
    return Data;
}

u32 XBmesensor2_Get_releaseBus_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RELEASEBUS_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_receivedSuccess(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RECEIVEDSUCCESS_DATA);
    return Data;
}

u32 XBmesensor2_Get_receivedSuccess_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_RECEIVEDSUCCESS_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_pressure_msb_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_MSB_I_DATA, Data);
}

u32 XBmesensor2_Get_pressure_msb_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_MSB_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_pressure_msb_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_MSB_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_pressure_msb_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_MSB_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_pressure_lsb_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_LSB_I_DATA, Data);
}

u32 XBmesensor2_Get_pressure_lsb_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_LSB_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_pressure_lsb_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_LSB_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_pressure_lsb_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_LSB_O_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_pressure_xlsb_i(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_XLSB_I_DATA, Data);
}

u32 XBmesensor2_Get_pressure_xlsb_i(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_XLSB_I_DATA);
    return Data;
}

u32 XBmesensor2_Get_pressure_xlsb_o(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_XLSB_O_DATA);
    return Data;
}

u32 XBmesensor2_Get_pressure_xlsb_o_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_PRESSURE_XLSB_O_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_stat_reg_val6_state(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STAT_REG_VAL6_STATE_DATA);
    return Data;
}

u32 XBmesensor2_Get_stat_reg_val6_state_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STAT_REG_VAL6_STATE_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_ctrl_reg_val2(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL2_DATA);
    return Data;
}

u32 XBmesensor2_Get_ctrl_reg_val2_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_VAL2_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_ctrl2RegState(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL2REGSTATE_DATA);
    return Data;
}

u32 XBmesensor2_Get_ctrl2RegState_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL2REGSTATE_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_ctrl_reg_check(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_CHECK_DATA);
    return Data;
}

u32 XBmesensor2_Get_ctrl_reg_check_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CTRL_REG_CHECK_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_zeroBytes(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_ZEROBYTES_DATA, Data);
}

u32 XBmesensor2_Get_zeroBytes(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_ZEROBYTES_DATA);
    return Data;
}

u32 XBmesensor2_Get_interrStatus3State(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3STATE_DATA);
    return Data;
}

u32 XBmesensor2_Get_interrStatus3State_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3STATE_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_interrStatus5State(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS5STATE_DATA);
    return Data;
}

u32 XBmesensor2_Get_interrStatus5State_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS5STATE_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_tx_fifo_1(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_TX_FIFO_1_DATA);
    return Data;
}

u32 XBmesensor2_Get_tx_fifo_1_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_TX_FIFO_1_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_tx_fifo_2(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_TX_FIFO_2_DATA);
    return Data;
}

u32 XBmesensor2_Get_tx_fifo_2_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_TX_FIFO_2_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_interrStatus(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS_DATA);
    return Data;
}

u32 XBmesensor2_Get_interrStatus_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_stat_reg_val(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STAT_REG_VAL_DATA);
    return Data;
}

u32 XBmesensor2_Get_stat_reg_val_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STAT_REG_VAL_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_statRegState(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STATREGSTATE_DATA);
    return Data;
}

u32 XBmesensor2_Get_statRegState_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_STATREGSTATE_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_clearInterrStatus(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEARINTERRSTATUS_DATA);
    return Data;
}

u32 XBmesensor2_Get_clearInterrStatus_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEARINTERRSTATUS_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_clearInterrStatusCheck(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEARINTERRSTATUSCHECK_DATA);
    return Data;
}

u32 XBmesensor2_Get_clearInterrStatusCheck_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_CLEARINTERRSTATUSCHECK_CTRL);
    return Data & 0x1;
}

void XBmesensor2_Set_error1(XBmesensor2 *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_ERROR1_DATA, Data);
}

u32 XBmesensor2_Get_error1(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_ERROR1_DATA);
    return Data;
}

u32 XBmesensor2_Get_tx_fifo_3(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_TX_FIFO_3_DATA);
    return Data;
}

u32 XBmesensor2_Get_tx_fifo_3_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_TX_FIFO_3_CTRL);
    return Data & 0x1;
}

u32 XBmesensor2_Get_interrStatus3(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3_DATA);
    return Data;
}

u32 XBmesensor2_Get_interrStatus3_vld(XBmesensor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_INTERRSTATUS3_CTRL);
    return Data & 0x1;
}

void XBmesensor2_InterruptGlobalEnable(XBmesensor2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_GIE, 1);
}

void XBmesensor2_InterruptGlobalDisable(XBmesensor2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_GIE, 0);
}

void XBmesensor2_InterruptEnable(XBmesensor2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_IER);
    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_IER, Register | Mask);
}

void XBmesensor2_InterruptDisable(XBmesensor2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_IER);
    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_IER, Register & (~Mask));
}

void XBmesensor2_InterruptClear(XBmesensor2 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XBmesensor2_WriteReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_ISR, Mask);
}

u32 XBmesensor2_InterruptGetEnabled(XBmesensor2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_IER);
}

u32 XBmesensor2_InterruptGetStatus(XBmesensor2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XBmesensor2_ReadReg(InstancePtr->Axilites_BaseAddress, XBMESENSOR2_AXILITES_ADDR_ISR);
}

