// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xbmesensor2.h"

extern XBmesensor2_Config XBmesensor2_ConfigTable[];

XBmesensor2_Config *XBmesensor2_LookupConfig(u16 DeviceId) {
	XBmesensor2_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBMESENSOR2_NUM_INSTANCES; Index++) {
		if (XBmesensor2_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBmesensor2_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBmesensor2_Initialize(XBmesensor2 *InstancePtr, u16 DeviceId) {
	XBmesensor2_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBmesensor2_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBmesensor2_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

